const VERSION = '1.0.0'

const ERROR_CODES = {
  NETWORK: 'NETWORK',
  TIMEOUT: 'TIMEOUT',
  ABORTED: 'ABORTED',
  HTTP_ERROR: 'HTTP_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_CONFIG: 'INVALID_CONFIG',
  SCRIPT_FIELD_DETECTED: 'SCRIPT_FIELD_DETECTED',
  PAYLOAD_TOO_DEEP: 'PAYLOAD_TOO_DEEP',
  PAYLOAD_TOO_MANY_KEYS: 'PAYLOAD_TOO_MANY_KEYS',
  CIRCULAR_REF: 'CIRCULAR_REF',
  TYPE_MISMATCH: 'TYPE_MISMATCH',
  CONFIG_EXPIRED: 'CONFIG_EXPIRED',
  SSR_NO_FETCH: 'SSR_NO_FETCH',
  UNKNOWN: 'UNKNOWN',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.NETWORK]: '网络错误',
  [ERROR_CODES.TIMEOUT]: '请求超时',
  [ERROR_CODES.ABORTED]: '请求被取消',
  [ERROR_CODES.HTTP_ERROR]: 'HTTP 状态码错误',
  [ERROR_CODES.INVALID_JSON]: '无效的 JSON',
  [ERROR_CODES.INVALID_CONFIG]: '无效的配置',
  [ERROR_CODES.SCRIPT_FIELD_DETECTED]: '检测到脚本字段，为安全起见已拒绝',
  [ERROR_CODES.PAYLOAD_TOO_DEEP]: 'Payload 嵌套深度超过限制',
  [ERROR_CODES.PAYLOAD_TOO_MANY_KEYS]: 'Payload 键数量超过限制',
  [ERROR_CODES.CIRCULAR_REF]: '检测到循环引用',
  [ERROR_CODES.TYPE_MISMATCH]: '类型不匹配',
  [ERROR_CODES.CONFIG_EXPIRED]: '配置已过期',
  [ERROR_CODES.SSR_NO_FETCH]: 'SSR 环境无 fetch 能力',
  [ERROR_CODES.UNKNOWN]: '未知错误',
}

const SOURCES = {
  REMOTE: 'remote',
  STATIC: 'static',
  DEFAULT: 'default',
}

const ENVIRONMENTS = {
  DEV: 'dev',
  STAGING: 'staging',
  PROD: 'prod',
}

const DEFAULT_TIMEOUT_MS = 8000
const MAX_TIMEOUT_MS = 60000
const MIN_TIMEOUT_MS = 0

const MAX_PAYLOAD_DEPTH = 5
const MAX_PAYLOAD_KEYS = 100

const DEFAULT_REFRESH_INTERVAL_MS = 60000
const MAX_REFRESH_INTERVAL_MS = 3600000

const EXPONENTIAL_BACKOFF = {
  INITIAL_DELAY_MS: 1000,
  MAX_DELAY_MS: 60000,
  MULTIPLIER: 2,
  MAX_ATTEMPTS: 5,
  JITTER_FACTOR: 0.1,
}

const SENSITIVE_KEY_PATTERN = /token|secret|password/i

const MAX_CAUSE_CHAIN_LENGTH = 5
const MAX_ERROR_MESSAGE_LENGTH = 2000

const DEFAULT_API_PATH = '/api/devtools/config'

const SCRIPT_KEY_PATTERNS = [
  /^script$/i,
  /^on[a-z]+$/i,
  /javascript:/i,
]

export {
  VERSION,
  ERROR_CODES,
  ERROR_MESSAGES,
  SOURCES,
  ENVIRONMENTS,
  DEFAULT_TIMEOUT_MS,
  MAX_TIMEOUT_MS,
  MIN_TIMEOUT_MS,
  MAX_PAYLOAD_DEPTH,
  MAX_PAYLOAD_KEYS,
  DEFAULT_REFRESH_INTERVAL_MS,
  MAX_REFRESH_INTERVAL_MS,
  EXPONENTIAL_BACKOFF,
  SENSITIVE_KEY_PATTERN,
  MAX_CAUSE_CHAIN_LENGTH,
  MAX_ERROR_MESSAGE_LENGTH,
  DEFAULT_API_PATH,
  SCRIPT_KEY_PATTERNS,
}
