import {
  ERROR_CODES,
  ERROR_MESSAGES,
  RECOVERY_HINTS,
  ANCHOR_POSITIONS,
  WATERMARK_TYPES,
  TILE_MODES,
  EXIF_ORIENTATIONS,
  DEFAULT_TEXT_WATERMARK,
  DEFAULT_IMAGE_WATERMARK,
  MAX_TEXTURE_SIZE,
  MAX_CANVAS_AREA,
  MEMORY_PER_PIXEL,
  SAFE_ZOOM_MIN,
  SAFE_ZOOM_MAX,
  ZOOM_STEP,
  WHEEL_ZOOM_FACTOR,
  EXIF_APP1_MARKER,
  EXIF_HEADER,
} from './constants.js'

import {
  getErrorMessage,
  getRecoveryHint,
  createError,
  createSuccess,
  createFailure,
  isValidErrorCode,
  wrapError,
} from './errors.js'

import {
  hasDangerousPatterns,
  escapeHtml,
  sanitizeText,
  sanitizeFilename,
  sanitizeColor,
  sanitizeFontFamily,
} from './sanitizer.js'

import {
  loadImage,
  loadImageFromBlob,
  loadImageFromDataUrl,
  loadImageWithCreateImageBitmap,
  parseExifOrientation,
  applyExifOrientation,
  calculateMemoryUsage,
  isImageTooLarge,
  getDownscaleFactor,
} from './imageLoader.js'

import {
  buildWatermarkPlan,
  calculateAnchorPosition,
  normalizeRotation,
  estimateTextDimensions,
  generateTilePositions,
  validateWatermarkConfig,
  calculatePlanMemory,
  buildTextWatermarkLayer,
  buildImageWatermarkLayer,
} from './watermarkPlan.js'

import {
  rasterizePreview,
  rasterizeCompare,
  canvasToBlob,
  canvasToDataUrl,
  downloadCanvas,
  createCanvas,
  getContext,
  drawTextWatermark,
  drawImageWatermark,
  drawLayer,
  drawBackground,
} from './rasterizer.js'

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  RECOVERY_HINTS,
  ANCHOR_POSITIONS,
  WATERMARK_TYPES,
  TILE_MODES,
  EXIF_ORIENTATIONS,
  DEFAULT_TEXT_WATERMARK,
  DEFAULT_IMAGE_WATERMARK,
  MAX_TEXTURE_SIZE,
  MAX_CANVAS_AREA,
  MEMORY_PER_PIXEL,
  SAFE_ZOOM_MIN,
  SAFE_ZOOM_MAX,
  ZOOM_STEP,
  WHEEL_ZOOM_FACTOR,
  EXIF_APP1_MARKER,
  EXIF_HEADER,

  getErrorMessage,
  getRecoveryHint,
  createError,
  createSuccess,
  createFailure,
  isValidErrorCode,
  wrapError,

  hasDangerousPatterns,
  escapeHtml,
  sanitizeText,
  sanitizeFilename,
  sanitizeColor,
  sanitizeFontFamily,

  loadImage,
  loadImageFromBlob,
  loadImageFromDataUrl,
  loadImageWithCreateImageBitmap,
  parseExifOrientation,
  applyExifOrientation,
  calculateMemoryUsage,
  isImageTooLarge,
  getDownscaleFactor,

  buildWatermarkPlan,
  calculateAnchorPosition,
  normalizeRotation,
  estimateTextDimensions,
  generateTilePositions,
  validateWatermarkConfig,
  calculatePlanMemory,
  buildTextWatermarkLayer,
  buildImageWatermarkLayer,

  rasterizePreview,
  rasterizeCompare,
  canvasToBlob,
  canvasToDataUrl,
  downloadCanvas,
  createCanvas,
  getContext,
  drawTextWatermark,
  drawImageWatermark,
  drawLayer,
  drawBackground,
}
