import { CATEGORIES } from './constants.js'

const MIME_TABLE_V1 = [
  {
    extension: 'html',
    mime: 'text/html',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'htm',
    mime: 'text/html',
    category: CATEGORIES.WEB,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'css',
    mime: 'text/css',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'js',
    mime: 'application/javascript',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'mjs',
    mime: 'application/javascript',
    category: CATEGORIES.WEB,
    priority: 95,
    isRecommended: false,
  },
  {
    extension: 'json',
    mime: 'application/json',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'xml',
    mime: 'application/xml',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'xhtml',
    mime: 'application/xhtml+xml',
    category: CATEGORIES.WEB,
    priority: 95,
    isRecommended: false,
  },
  {
    extension: 'svg',
    mime: 'image/svg+xml',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'txt',
    mime: 'text/plain',
    category: CATEGORIES.OTHER,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'log',
    mime: 'text/plain',
    category: CATEGORIES.OTHER,
    priority: 80,
    isRecommended: false,
  },
  {
    extension: 'md',
    mime: 'text/markdown',
    category: CATEGORIES.OTHER,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'markdown',
    mime: 'text/markdown',
    category: CATEGORIES.OTHER,
    priority: 90,
    isRecommended: false,
  },
]

const MIME_TABLE_V2 = [
  ...MIME_TABLE_V1,
  {
    extension: 'png',
    mime: 'image/png',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'jpg',
    mime: 'image/jpeg',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'jpeg',
    mime: 'image/jpeg',
    category: CATEGORIES.MEDIA,
    priority: 95,
    isRecommended: false,
  },
  {
    extension: 'gif',
    mime: 'image/gif',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'webp',
    mime: 'image/webp',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'avif',
    mime: 'image/avif',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'ico',
    mime: 'image/x-icon',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'bmp',
    mime: 'image/bmp',
    category: CATEGORIES.MEDIA,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'tiff',
    mime: 'image/tiff',
    category: CATEGORIES.MEDIA,
    priority: 85,
    isRecommended: false,
  },
  {
    extension: 'tif',
    mime: 'image/tiff',
    category: CATEGORIES.MEDIA,
    priority: 80,
    isRecommended: false,
  },
  {
    extension: 'mp3',
    mime: 'audio/mpeg',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'wav',
    mime: 'audio/wav',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'ogg',
    mime: 'audio/ogg',
    category: CATEGORIES.MEDIA,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'flac',
    mime: 'audio/flac',
    category: CATEGORIES.MEDIA,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'aac',
    mime: 'audio/aac',
    category: CATEGORIES.MEDIA,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'mp4',
    mime: 'video/mp4',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'webm',
    mime: 'video/webm',
    category: CATEGORIES.MEDIA,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'mkv',
    mime: 'video/x-matroska',
    category: CATEGORIES.MEDIA,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'avi',
    mime: 'video/x-msvideo',
    category: CATEGORIES.MEDIA,
    priority: 85,
    isRecommended: false,
  },
  {
    extension: 'mov',
    mime: 'video/quicktime',
    category: CATEGORIES.MEDIA,
    priority: 85,
    isRecommended: false,
  },
  {
    extension: 'pdf',
    mime: 'application/pdf',
    category: CATEGORIES.OFFICE,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'doc',
    mime: 'application/msword',
    category: CATEGORIES.OFFICE,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    category: CATEGORIES.OFFICE,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'xls',
    mime: 'application/vnd.ms-excel',
    category: CATEGORIES.OFFICE,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: CATEGORIES.OFFICE,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'ppt',
    mime: 'application/vnd.ms-powerpoint',
    category: CATEGORIES.OFFICE,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'pptx',
    mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    category: CATEGORIES.OFFICE,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'odt',
    mime: 'application/vnd.oasis.opendocument.text',
    category: CATEGORIES.OFFICE,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'ods',
    mime: 'application/vnd.oasis.opendocument.spreadsheet',
    category: CATEGORIES.OFFICE,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'odp',
    mime: 'application/vnd.oasis.opendocument.presentation',
    category: CATEGORIES.OFFICE,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'zip',
    mime: 'application/zip',
    category: CATEGORIES.COMPRESSION,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'rar',
    mime: 'application/vnd.rar',
    category: CATEGORIES.COMPRESSION,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: '7z',
    mime: 'application/x-7z-compressed',
    category: CATEGORIES.COMPRESSION,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'tar',
    mime: 'application/x-tar',
    category: CATEGORIES.COMPRESSION,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'gz',
    mime: 'application/gzip',
    category: CATEGORIES.COMPRESSION,
    priority: 90,
    isRecommended: true,
  },
  {
    extension: 'gzip',
    mime: 'application/gzip',
    category: CATEGORIES.COMPRESSION,
    priority: 80,
    isRecommended: false,
  },
  {
    extension: 'bz2',
    mime: 'application/x-bzip2',
    category: CATEGORIES.COMPRESSION,
    priority: 85,
    isRecommended: false,
  },
  {
    extension: 'xz',
    mime: 'application/x-xz',
    category: CATEGORIES.COMPRESSION,
    priority: 85,
    isRecommended: false,
  },
  {
    extension: 'wasm',
    mime: 'application/wasm',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'woff',
    mime: 'font/woff',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'woff2',
    mime: 'font/woff2',
    category: CATEGORIES.WEB,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'ttf',
    mime: 'font/ttf',
    category: CATEGORIES.WEB,
    priority: 95,
    isRecommended: false,
  },
  {
    extension: 'otf',
    mime: 'font/otf',
    category: CATEGORIES.WEB,
    priority: 95,
    isRecommended: false,
  },
  {
    extension: 'eot',
    mime: 'application/vnd.ms-fontobject',
    category: CATEGORIES.WEB,
    priority: 80,
    isRecommended: false,
  },
  {
    extension: 'csv',
    mime: 'text/csv',
    category: CATEGORIES.OFFICE,
    priority: 100,
    isRecommended: true,
  },
  {
    extension: 'yaml',
    mime: 'application/yaml',
    category: CATEGORIES.WEB,
    priority: 95,
    isRecommended: true,
  },
  {
    extension: 'yml',
    mime: 'application/yaml',
    category: CATEGORIES.WEB,
    priority: 90,
    isRecommended: false,
  },
  {
    extension: 'toml',
    mime: 'application/toml',
    category: CATEGORIES.WEB,
    priority: 90,
    isRecommended: true,
  },
  {
    extension: 'ini',
    mime: 'text/plain',
    category: CATEGORIES.OTHER,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'conf',
    mime: 'text/plain',
    category: CATEGORIES.OTHER,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'rtf',
    mime: 'application/rtf',
    category: CATEGORIES.OFFICE,
    priority: 85,
    isRecommended: false,
  },
  {
    extension: 'epub',
    mime: 'application/epub+zip',
    category: CATEGORIES.OTHER,
    priority: 90,
    isRecommended: true,
  },
  {
    extension: 'jar',
    mime: 'application/java-archive',
    category: CATEGORIES.COMPRESSION,
    priority: 80,
    isRecommended: false,
  },
  {
    extension: 'apk',
    mime: 'application/vnd.android.package-archive',
    category: CATEGORIES.COMPRESSION,
    priority: 80,
    isRecommended: false,
  },
  {
    extension: 'ipa',
    mime: 'application/octet-stream',
    category: CATEGORIES.COMPRESSION,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'dmg',
    mime: 'application/x-apple-diskimage',
    category: CATEGORIES.COMPRESSION,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'exe',
    mime: 'application/vnd.microsoft.portable-executable',
    category: CATEGORIES.OTHER,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'msi',
    mime: 'application/x-msi',
    category: CATEGORIES.OTHER,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'deb',
    mime: 'application/vnd.debian.binary-package',
    category: CATEGORIES.COMPRESSION,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'rpm',
    mime: 'application/x-rpm',
    category: CATEGORIES.COMPRESSION,
    priority: 70,
    isRecommended: false,
  },
  {
    extension: 'bin',
    mime: 'application/octet-stream',
    category: CATEGORIES.OTHER,
    priority: 60,
    isRecommended: false,
  },
]

const MIME_TABLES = {
  v1: MIME_TABLE_V1,
  v2: MIME_TABLE_V2,
}

const MAGIC_NUMBERS = [
  {
    signature: [0x25, 0x50, 0x44, 0x46],
    mime: 'application/pdf',
    description: 'PDF document',
  },
  {
    signature: [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A],
    mime: 'image/png',
    description: 'PNG image',
  },
  {
    signature: [0xFF, 0xD8, 0xFF],
    mime: 'image/jpeg',
    description: 'JPEG image',
  },
  {
    signature: [0x47, 0x49, 0x46, 0x38],
    mime: 'image/gif',
    description: 'GIF image',
  },
  {
    signature: [0x52, 0x49, 0x46, 0x46],
    mime: 'image/webp',
    description: 'WebP image',
    offset: 0,
    trailingCheck: {
      offset: 8,
      signature: [0x57, 0x45, 0x42, 0x50],
    },
  },
  {
    signature: [0x50, 0x4B, 0x03, 0x04],
    mime: 'application/zip',
    description: 'ZIP archive',
    canBeOfficeOpenXml: true,
  },
  {
    signature: [0x50, 0x4B, 0x05, 0x06],
    mime: 'application/zip',
    description: 'ZIP archive (empty)',
  },
  {
    signature: [0x50, 0x4B, 0x07, 0x08],
    mime: 'application/zip',
    description: 'ZIP archive (spanned)',
  },
  {
    signature: [0x52, 0x61, 0x72, 0x21, 0x1A, 0x07],
    mime: 'application/vnd.rar',
    description: 'RAR archive',
  },
  {
    signature: [0x37, 0x7A, 0xBC, 0xAF, 0x27, 0x1C],
    mime: 'application/x-7z-compressed',
    description: '7-Zip archive',
  },
  {
    signature: [0x1F, 0x8B],
    mime: 'application/gzip',
    description: 'GZIP compressed',
  },
  {
    signature: [0x42, 0x5A, 0x68],
    mime: 'application/x-bzip2',
    description: 'BZIP2 compressed',
  },
  {
    signature: [0xFD, 0x37, 0x7A, 0x58, 0x5A, 0x00],
    mime: 'application/x-xz',
    description: 'XZ compressed',
  },
  {
    signature: [0x4D, 0x5A],
    mime: 'application/vnd.microsoft.portable-executable',
    description: 'Windows executable (PE)',
  },
  {
    signature: [0x7F, 0x45, 0x4C, 0x46],
    mime: 'application/octet-stream',
    description: 'ELF binary',
  },
  {
    signature: [0x42, 0x4D],
    mime: 'image/bmp',
    description: 'BMP image',
  },
  {
    signature: [0x00, 0x00, 0x00, 0x00, 0x66, 0x74, 0x79, 0x70],
    mime: 'video/mp4',
    description: 'MP4 video',
  },
  {
    signature: [0x1A, 0x45, 0xDF, 0xA3],
    mime: 'video/webm',
    description: 'WebM/Matroska video',
  },
  {
    signature: [0x49, 0x44, 0x33],
    mime: 'audio/mpeg',
    description: 'MP3 audio (with ID3v2 tag)',
  },
  {
    signature: [0xFF, 0xFB],
    mime: 'audio/mpeg',
    description: 'MP3 audio',
  },
  {
    signature: [0xFF, 0xFA],
    mime: 'audio/mpeg',
    description: 'MP3 audio',
  },
  {
    signature: [0x52, 0x49, 0x46, 0x46],
    mime: 'audio/wav',
    description: 'WAV audio',
    offset: 0,
    trailingCheck: {
      offset: 8,
      signature: [0x57, 0x41, 0x56, 0x45],
    },
  },
  {
    signature: [0x4F, 0x67, 0x67, 0x53],
    mime: 'audio/ogg',
    description: 'OGG audio',
  },
  {
    signature: [0x66, 0x4C, 0x61, 0x43],
    mime: 'audio/flac',
    description: 'FLAC audio',
  },
  {
    signature: [0x3C, 0x3F, 0x78, 0x6D, 0x6C],
    mime: 'application/xml',
    description: 'XML document',
  },
  {
    signature: [0xEF, 0xBB, 0xBF],
    mime: 'text/plain',
    description: 'UTF-8 BOM text',
  },
]

const OFFICE_OPEN_XML_DETECTION = [
  {
    entryPath: '[Content_Types].xml',
    subTypes: [
      { pattern: 'wordprocessingml', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', extension: 'docx' },
      { pattern: 'spreadsheetml', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', extension: 'xlsx' },
      { pattern: 'presentationml', mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', extension: 'pptx' },
    ],
  },
]

function getTableByVersion(version) {
  return MIME_TABLES[version] || MIME_TABLES.v2
}

function getAllVersions() {
  return Object.keys(MIME_TABLES)
}

export {
  MIME_TABLES,
  MIME_TABLE_V1,
  MIME_TABLE_V2,
  MAGIC_NUMBERS,
  OFFICE_OPEN_XML_DETECTION,
  getTableByVersion,
  getAllVersions,
}
