const HISTORY_MODES = {
  PUSH: 'push',
  REPLACE: 'replace',
}

const STORAGE_KEYS = {
  LAST_SUCCESSFUL_STATE: 'route_sync_last_successful_state',
}

const URL_LIMITS = {
  MAX_TOTAL_LENGTH: 2048,
  MAX_QUERY_STRING_LENGTH: 2000,
  KEY_REGEX: /^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z0-9_]+)*$/,
}

const WARNING_CODES = {
  INVALID_PARAM: 'INVALID_PARAM',
  INVALID_PERCENT_SEQUENCE: 'INVALID_PERCENT_SEQUENCE',
  INVALID_BOOLEAN: 'INVALID_BOOLEAN',
  INVALID_NUMBER: 'INVALID_NUMBER',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
  INVALID_KEY_FORMAT: 'INVALID_KEY_FORMAT',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
  VALUE_TRUNCATED: 'VALUE_TRUNCATED',
  URL_LENGTH_EXCEEDED: 'URL_LENGTH_EXCEEDED',
  HISTORY_API_UNAVAILABLE: 'HISTORY_API_UNAVAILABLE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
}

const BOOLEAN_TRUE_STRINGS = ['true', '1', 'yes', 'on']
const BOOLEAN_FALSE_STRINGS = ['false', '0', 'no', 'off']

export {
  HISTORY_MODES,
  STORAGE_KEYS,
  URL_LIMITS,
  WARNING_CODES,
  BOOLEAN_TRUE_STRINGS,
  BOOLEAN_FALSE_STRINGS,
}
