const CASE_STYLES = {
  CAMEL_CASE: 'camelCase',
  PASCAL_CASE: 'PascalCase',
  SNAKE_CASE: 'snake_case',
  SCREAMING_SNAKE: 'SCREAMING_SNAKE',
  KEBAB_CASE: 'kebab-case',
  TRAIN_CASE: 'Train-Case',
}

const CASE_STYLE_LABELS = {
  [CASE_STYLES.CAMEL_CASE]: 'camelCase',
  [CASE_STYLES.PASCAL_CASE]: 'PascalCase',
  [CASE_STYLES.SNAKE_CASE]: 'snake_case',
  [CASE_STYLES.SCREAMING_SNAKE]: 'SCREAMING_SNAKE',
  [CASE_STYLES.KEBAB_CASE]: 'kebab-case',
  [CASE_STYLES.TRAIN_CASE]: 'Train-Case',
}

const ACRONYM_STRATEGIES = {
  ALL_UPPERCASE_BLOCK: 'allUppercaseBlock',
  FIRST_LETTER_ACRONYM: 'firstLetterAcronym',
  APPLE_STYLE: 'appleStyle',
}

const ACRONYM_STRATEGY_LABELS = {
  [ACRONYM_STRATEGIES.ALL_UPPERCASE_BLOCK]: '全大写块',
  [ACRONYM_STRATEGIES.FIRST_LETTER_ACRONYM]: '首字母缩略词',
  [ACRONYM_STRATEGIES.APPLE_STYLE]: 'Apple 风格',
}

const NUMBER_ATTACH_STRATEGIES = {
  ATTACH_PREVIOUS: 'attachPrevious',
  ATTACH_NEXT: 'attachNext',
  SEPARATE_SEGMENT: 'separateSegment',
}

const NUMBER_ATTACH_STRATEGY_LABELS = {
  [NUMBER_ATTACH_STRATEGIES.ATTACH_PREVIOUS]: '附着前段',
  [NUMBER_ATTACH_STRATEGIES.ATTACH_NEXT]: '附着后段',
  [NUMBER_ATTACH_STRATEGIES.SEPARATE_SEGMENT]: '独立段',
}

const ILLEGAL_CHAR_MODES = {
  PRESERVE: 'preserve',
  REJECT: 'reject',
}

const ILLEGAL_CHAR_MODE_LABELS = {
  [ILLEGAL_CHAR_MODES.PRESERVE]: '保留原始非字母数字字符',
  [ILLEGAL_CHAR_MODES.REJECT]: '严格拒绝非法字符',
}

const COMPRESSION_STRATEGIES = {
  NONE: 'none',
  COMPRESS_LEADING: 'compressLeading',
  COMPRESS_TRAILING: 'compressTrailing',
  COMPRESS_CONSECUTIVE: 'compressConsecutive',
  COMPRESS_ALL: 'compressAll',
}

const COMPRESSION_STRATEGY_LABELS = {
  [COMPRESSION_STRATEGIES.NONE]: '不压缩',
  [COMPRESSION_STRATEGIES.COMPRESS_LEADING]: '压缩首尾',
  [COMPRESSION_STRATEGIES.COMPRESS_CONSECUTIVE]: '压缩连续',
  [COMPRESSION_STRATEGIES.COMPRESS_ALL]: '压缩首尾与连续',
}

const UNICODE_MODES = {
  ASCII_ONLY: 'asciiOnly',
  ALLOW_UNICODE: 'allowUnicode',
}

const UNICODE_MODE_LABELS = {
  [UNICODE_MODES.ASCII_ONLY]: '仅 ASCII',
  [UNICODE_MODES.ALLOW_UNICODE]: '允许 Unicode',
}

const EXAMPLE_IDENTIFIERS = [
  'HTTPResponse',
  'XML2JSON',
  '__private',
  'userName',
  'UserID',
  'MY_CONSTANT',
  'my-component',
  'My-Component',
  'parseCSVFile',
  'APIv2Endpoint',
  'hello_world_v3',
  'mixed123with456Numbers',
  'UTF8Encoding',
  'getHTTPResponseCode',
  'IOError',
]

const MAX_INPUT_LINES = 1000
const MAX_LINE_LENGTH = 10000
const THROTTLE_DELAY_MS = 150

const STORAGE_KEY = 'identifierCaseConverter:recentSettings'

export {
  CASE_STYLES,
  CASE_STYLE_LABELS,
  ACRONYM_STRATEGIES,
  ACRONYM_STRATEGY_LABELS,
  NUMBER_ATTACH_STRATEGIES,
  NUMBER_ATTACH_STRATEGY_LABELS,
  ILLEGAL_CHAR_MODES,
  ILLEGAL_CHAR_MODE_LABELS,
  COMPRESSION_STRATEGIES,
  COMPRESSION_STRATEGY_LABELS,
  UNICODE_MODES,
  UNICODE_MODE_LABELS,
  EXAMPLE_IDENTIFIERS,
  MAX_INPUT_LINES,
  MAX_LINE_LENGTH,
  THROTTLE_DELAY_MS,
  STORAGE_KEY,
}
