const VERSION = '1.0.0'

const DOMAINS = {
  HTTP: 'http',
  WS: 'ws',
  CLIPBOARD: 'clipboard',
  STORAGE: 'storage',
  UNKNOWN: 'unknown',
}

const SEVERITY = {
  DEBUG: 'debug',
  INFO: 'info',
  WARNING: 'warning',
  ERROR: 'error',
  FATAL: 'fatal',
}

const ERROR_CODES = {
  UNKNOWN_BUSINESS: 'UNKNOWN_BUSINESS',
  UNKNOWN_DOMAIN: 'UNKNOWN_DOMAIN',
  INVALID_PATCH: 'INVALID_PATCH',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  ABORTED: 'ABORTED',
  HTTP_400: 'HTTP_400',
  HTTP_401: 'HTTP_401',
  HTTP_403: 'HTTP_403',
  HTTP_404: 'HTTP_404',
  HTTP_429: 'HTTP_429',
  HTTP_500: 'HTTP_500',
  HTTP_503: 'HTTP_503',
  WS_CONNECTION_FAILED: 'WS_CONNECTION_FAILED',
  WS_PROTOCOL_ERROR: 'WS_PROTOCOL_ERROR',
  CLIPBOARD_PERMISSION_DENIED: 'CLIPBOARD_PERMISSION_DENIED',
  CLIPBOARD_NOT_SUPPORTED: 'CLIPBOARD_NOT_SUPPORTED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_DISABLED: 'STORAGE_DISABLED',
}

const DEFAULT_LOCALES = ['zh', 'en']

const DEFAULT_RETRYABLE_HTTP_STATUS = new Set([408, 429, 500, 502, 503, 504])

const DEFAULT_RETRY_DELAY_SECONDS = 1

const DEFAULT_RETRY_MAX_DELAY_SECONDS = 60

const MAX_CAUSE_CHAIN_DEPTH = 5

const MAX_ERROR_MESSAGE_LENGTH = 2000

const MAX_MAPPING_TABLE_SIZE = 1000

const MAX_PATCH_FETCH_TIMEOUT_MS = 5000

const DEFAULT_PATCH_URL = ''

const ENVIRONMENTS = {
  DEVELOPMENT: 'development',
  STAGING: 'staging',
  PRODUCTION: 'production',
}

export {
  VERSION,
  DOMAINS,
  SEVERITY,
  ERROR_CODES,
  DEFAULT_LOCALES,
  DEFAULT_RETRYABLE_HTTP_STATUS,
  DEFAULT_RETRY_DELAY_SECONDS,
  DEFAULT_RETRY_MAX_DELAY_SECONDS,
  MAX_CAUSE_CHAIN_DEPTH,
  MAX_ERROR_MESSAGE_LENGTH,
  MAX_MAPPING_TABLE_SIZE,
  MAX_PATCH_FETCH_TIMEOUT_MS,
  DEFAULT_PATCH_URL,
  ENVIRONMENTS,
}
