const VERSION = '1.0.0'

const BREAKPOINTS = {
  NARROW: 640,
  MEDIUM: 1024,
  WIDE: 1440,
}

const SORT_STRATEGIES = {
  CATEGORY: 'category',
  TAG: 'tag',
  RECENT: 'recent',
  ID: 'id',
  TITLE: 'title',
}

const TOOL_STATUSES = {
  STABLE: 'stable',
  BETA: 'beta',
  DEPRECATED: 'deprecated',
}

const ERROR_CODES = {
  INVALID_TOOL_ID: 'INVALID_TOOL_ID',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  LIST_LOAD_FAILED: 'LIST_LOAD_FAILED',
  EMPTY_LIST: 'EMPTY_LIST',
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  INVALID_QUERY_PARAM: 'INVALID_QUERY_PARAM',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_TOOL_ID]: '无效的工具 ID',
  [ERROR_CODES.TOOL_NOT_FOUND]: '工具不存在',
  [ERROR_CODES.LIST_LOAD_FAILED]: '工具清单加载失败',
  [ERROR_CODES.EMPTY_LIST]: '工具清单为空',
  [ERROR_CODES.SCHEMA_VALIDATION_FAILED]: '部分条目校验失败',
  [ERROR_CODES.INVALID_QUERY_PARAM]: '无效的查询参数',
}

const QUERY_PARAMS = {
  SIDEBAR_COLLAPSED: 'sidebar',
  SEARCH_QUERY: 'q',
  SORT_STRATEGY: 'sort',
}

const DEFAULT_SIDEBAR_WIDTH = 280
const COLLAPSED_SIDEBAR_WIDTH = 0
const HEADER_HEIGHT = 56

const VIRTUALIZATION_CONFIG = {
  ITEM_HEIGHT: 56,
  BUFFER_ITEMS: 5,
  THRESHOLD: 100,
}

const STORAGE_KEYS = {
  RECENT_TOOLS: 'app_shell_recent_tools',
}

const MAX_RECENT_TOOLS = 10

const DEMO_TOOLS_COUNT = 20

export {
  VERSION,
  BREAKPOINTS,
  SORT_STRATEGIES,
  TOOL_STATUSES,
  ERROR_CODES,
  ERROR_MESSAGES,
  QUERY_PARAMS,
  DEFAULT_SIDEBAR_WIDTH,
  COLLAPSED_SIDEBAR_WIDTH,
  HEADER_HEIGHT,
  VIRTUALIZATION_CONFIG,
  STORAGE_KEYS,
  MAX_RECENT_TOOLS,
  DEMO_TOOLS_COUNT,
}
