const PINYIN_DICT = {
  a: 'a阿啊呵腌嗄',
  ai: '爱埃挨唉矮碍艾哀唉哎挨皑癌蔼霭隘暧嗌',
  an: '安按暗岸案鞍俺胺谙铵黯桉铵',
  ang: '昂肮盎',
  ao: '奥熬傲袄凹澳翱鏖遨嗷遨獒鳌',
  ba: '巴把吧八拔爸霸罢扒疤笆靶坝捌跋粑鲅魃',
  bai: '白百拜败柏摆伯稗捭',
  ban: '办半班版板般伴搬斑颁扮扳坂钣瓣拌绊',
  bang: '帮榜绑棒磅蚌邦傍谤膀镑梆',
  bao: '包保报宝抱饱暴豹剥雹褒苞鲍胞曝',
  bei: '被北背杯辈悲备倍碑贝臂卑焙悖惫蓓狈悖',
  ben: '本奔苯笨畚',
  beng: '崩绷甭泵迸嘣蚌',
  bi: '比必笔碧闭彼毕避逼弊鄙壁臂庇痹泌荸秕痹',
  bian: '边变便编遍辩辨扁鞭贬砭卞汴弁苄煸',
  biao: '表标彪膘镖飚裱鳔',
  bie: '别鳖憋瘪',
  bin: '宾滨彬斌濒傧摈槟殡膑',
  bing: '并病冰兵饼丙秉柄禀摒',
  bo: '波博播拨剥薄伯驳勃泊菠搏膊舶箔魄簸',
  bu: '不部步布补捕卜哺埠簿埔怖',
  cai: '才材财裁采彩踩菜猜蔡',
  can: '参餐残蚕惭灿惨掺璨粲',
  cang: '藏仓苍舱沧',
  cao: '草操曹槽糙嘈螬',
  ce: '册测侧策厕恻',
  ceng: '层蹭曾',
  cha: '查差插茶察叉茬喳碴诧姹刹',
  chai: '拆柴豺',
  chan: '产缠颤掺蝉馋谗潺蟾婵禅廛',
  chang: '长常场厂唱畅昌倡尝偿肠敞徜嫦',
  chao: '超抄钞朝潮炒吵巢嘲焯',
  che: '车彻扯掣澈辙',
  chen: '陈称沉晨臣尘衬忱谌谶',
  cheng: '成城程称承乘诚呈盛惩澄丞骋秤',
  chi: '吃迟持尺翅赤池驰耻斥痴匙侈炽饬嗤',
  chong: '充冲虫重崇宠憧铳',
  chou: '抽丑愁仇筹稠瞅绸畴踌酬惆',
  chu: '出除处初触楚础储畜厨雏锄杵黜',
  chuai: '揣踹衰',
  chuan: '传穿船川串喘钏',
  chuang: '创窗床闯幢疮怆',
  chui: '吹垂锤炊捶槌椎',
  chun: '春纯唇蠢醇淳椿鹑',
  chuo: '戳绰辍龊啜',
  ci: '次此词磁刺瓷慈辞茨祠糍',
  cong: '从丛聪葱囱匆琮',
  cou: '凑辏',
  cu: '促粗簇醋蹴蹙',
  cuan: '窜篡攒蹿蹿',
  cui: '催脆翠摧崔悴粹瘁啐',
  cun: '村存寸忖',
  cuo: '错措挫撮蹉痤磋',
  da: '大打答搭瘩鞑嗒',
  dai: '代带待袋逮戴怠殆傣甙歹贷',
  dan: '单担但旦诞弹蛋淡丹胆儋郸殚掸',
  dang: '当党档荡挡凼裆',
  dao: '到道倒导刀岛稻蹈盗悼祷',
  de: '的得德',
  deng: '等灯登凳邓瞪噔蹬',
  di: '的地底第低敌抵笛嫡滴迪堤涤狄',
  dia: '嗲',
  dian: '点电店典淀垫滇颠巅碘癫殿靛',
  diao: '掉调吊叼雕钓貂凋碉',
  die: '跌碟叠谍蝶牒爹耋',
  ding: '定顶钉订丁盯叮鼎锭啶',
  diu: '丢',
  dong: '东懂动冬冻洞董栋懂咚侗',
  dou: '都斗豆逗抖陡兜痘窦',
  du: '度读独毒堵都杜渡赌镀妒肚笃',
  duan: '段断短端锻缎椴',
  dui: '对队堆兑怼',
  dun: '吨顿蹲敦墩盾沌囤钝遁',
  duo: '多朵夺躲堕惰垛跺舵踱',
  e: '饿恶额俄鹅蛾峨讹鄂鳄愕噩萼谔',
  en: '恩蒽摁',
  er: '二而儿耳尔饵迩洱贰',
  fa: '发法罚乏伐阀筏砝',
  fan: '番翻凡烦反饭返范犯矾繁樊蕃幡',
  fang: '方放防房访仿芳妨纺肪舫坊枋',
  fei: '非飞肥费废菲匪诽啡扉蜚翡腓',
  fen: '分份芬粉奋纷愤粪氛汾忿吩',
  feng: '风封丰逢蜂缝疯奉凤讽烽锋冯',
  fo: '佛',
  fou: '否缶',
  fu: '福服富付复负妇父附扶府辅腐符伏俘浮拂氟幅袱幅芙',
  ga: '嘎噶胳',
  gai: '该改概盖钙丐芥垓',
  gan: '干感敢杆甘肝赶赣尴秆淦',
  gang: '刚钢港岗杠纲扛戆',
  gao: '高搞告稿糕羔篙皋',
  ge: '个哥歌格各革阁隔葛戈鸽胳搁咯骼',
  gei: '给',
  gen: '跟根亘',
  geng: '更耕庚羹梗耿',
  gong: '工公功供共攻宫恭龚躬巩拱汞贡',
  gou: '够够沟勾构购狗苟钩篝苟',
  gu: '古故顾固骨估股谷孤菇咕辜呱沽雇钴',
  gua: '挂瓜刮寡呱褂',
  guai: '怪乖拐',
  guan: '关观管官贯馆冠灌罐棺莞盥',
  guang: '光广逛胱',
  gui: '规归贵柜鬼轨桂闺诡跪瑰圭鲑',
  gun: '滚棍辊磙',
  guo: '国过果裹锅郭聒',
  ha: '哈蛤',
  hai: '还海害孩咳亥骸骇',
  han: '汉含寒函韩罕喊旱汗翰憾悍撼菡',
  hang: '行航杭巷夯',
  hao: '好号豪毫耗浩蒿濠嚎',
  he: '和合河核何贺喝鹤赫荷盒涸褐吓',
  hei: '黑嘿',
  hen: '很恨狠痕',
  heng: '横恒亨哼衡',
  hong: '红洪宏轰鸿虹弘闳泓',
  hou: '后候厚吼侯喉猴瘊',
  hu: '户护忽湖虎胡互呼壶蝴弧葫瑚扈唬',
  hua: '化画花华话划哗滑猾豁',
  huai: '坏怀槐徊淮踝',
  huan: '换还环缓欢幻焕患宦浣豢',
  huang: '黄荒慌皇惶煌晃谎幌湟凰璜篁',
  hui: '会回惠辉挥灰汇徽恢慧悔毁绘贿秽讳烩卉彗',
  hun: '混婚魂浑昏荤珲',
  huo: '或活火获货伙惑祸豁霍藿',
  ji: '及即机级集记计己几季基激急极际吉击绩籍激汲嫉脊',
  jia: '家加假价甲架夹佳嘉稼嫁钾枷葭',
  jian: '建见间件简剑减监坚尖键剪俭健煎歼涧溅柬缄',
  jiang: '将江讲降疆姜奖蒋酱桨僵疆犟',
  jiao: '叫教交角脚较胶骄浇娇蕉嚼焦椒佼皎',
  jie: '接节结解界洁接截揭杰街阶借皆睫婕',
  jin: '进近今金尽紧禁浸劲晋襟筋锦槿',
  jing: '经精景静敬京镜竞境径荆茎惊晶井警靖粳',
  jiong: '炯窘迥',
  jiu: '就九久酒旧究救纠揪臼玖疚赳',
  ju: '局举句距据巨具剧聚拒矩咀橘菊沮莒',
  juan: '卷捐倦眷娟涓鹃镌',
  jue: '绝觉决角掘嚼爵倔攫',
  jun: '军君均菌俊峻竣郡钧浚',
  ka: '卡咔咖',
  kai: '开凯慨楷揩铠',
  kan: '看砍刊堪勘坎侃瞰',
  kang: '康抗扛亢慷糠',
  kao: '考靠烤拷铐',
  ke: '可科刻克课客壳咳渴柯颗磕瞌',
  ken: '肯恳垦啃',
  keng: '坑吭铿',
  kong: '空控孔恐',
  kou: '口扣寇叩',
  ku: '苦哭库裤酷枯窟骷',
  kua: '夸跨垮挎',
  kuai: '快块筷侩脍',
  kuan: '宽款',
  kuang: '矿况框狂旷筐匡诓眶',
  kui: '亏愧窥葵魁馈溃睽傀',
  kun: '困昆捆坤鲲',
  kuo: '扩阔括廓',
  la: '拉腊蜡辣啦喇邋',
  lai: '来赖莱睐',
  lan: '兰蓝烂懒拦栏篮览滥婪澜',
  lang: '浪郎朗廊狼琅榔',
  lao: '老捞劳牢涝唠姥痨',
  le: '了乐勒',
  lei: '类累雷泪垒勒蕾磊擂镭',
  leng: '冷愣棱',
  li: '里理力立例礼离李利粒历厉励丽黎璃狸梨犁漓篱罹',
  lia: '俩',
  lian: '连脸练联恋莲链廉镰涟琏',
  liang: '两量良亮凉梁粮粱谅晾踉',
  liao: '了料聊疗寥辽燎撩缭',
  lie: '列烈裂猎劣冽咧',
  lin: '林临邻淋琳磷霖鳞蔺凛',
  ling: '零令灵领岭玲铃凌陵龄羚聆',
  liu: '六流留刘柳硫溜瘤浏馏',
  long: '龙隆笼聋拢垄珑',
  lou: '楼漏搂篓偻髅',
  lu: '路录陆卢鲁炉卤掳禄鹿麓碌漉',
  lv: '绿律旅虑滤履屡缕侣铝膂',
  luan: '乱卵滦峦孪挛',
  lun: '论轮伦沦抡纶',
  luo: '落罗络洛螺骆逻萝锣箩骡',
  ma: '马妈吗麻骂码嘛玛蚂摩',
  mai: '买卖埋迈麦脉',
  man: '满慢瞒蛮曼蔓馒谩',
  mang: '忙茫盲芒莽',
  mao: '猫毛矛茅茂帽贸冒貌卯耄',
  me: '么',
  mei: '没每美妹眉梅媒煤霉枚玫昧魅',
  men: '们门闷扪焖',
  meng: '猛梦蒙盟萌孟朦氓',
  mi: '米密迷谜眯弥蜜觅靡幂',
  mian: '面棉免绵眠冕缅娩湎',
  miao: '秒苗妙庙描瞄渺藐',
  mie: '灭蔑篾',
  min: '民敏闵泯抿皿',
  ming: '明名命鸣冥铭茗',
  miu: '谬',
  mo: '摸末墨默莫抹磨魔漠膜模陌摩谟',
  mou: '某谋牟眸',
  mu: '母木目牧幕慕墓穆沐募睦',
  na: '那拿哪纳呐娜钠衲',
  nai: '乃奶奈耐',
  nan: '男南难楠赧',
  nang: '囊',
  nao: '脑闹恼挠瑙',
  ne: '呢',
  nei: '内',
  nen: '嫩',
  neng: '能',
  ni: '你泥拟逆溺倪妮匿霓',
  nian: '年念粘撵碾蔫',
  niang: '娘酿',
  niao: '鸟尿袅',
  nie: '捏聂镍涅孽啮',
  nin: '您',
  ning: '宁凝拧柠',
  niu: '牛扭钮妞',
  nong: '农浓弄侬',
  nu: '努怒奴弩',
  nv: '女',
  nuan: '暖',
  nuo: '诺挪懦糯',
  o: '哦',
  ou: '欧偶呕藕殴鸥讴',
  pa: '怕爬帕扒趴啪琶',
  pai: '派拍排牌徘湃',
  pan: '判盘攀潘畔判胖',
  pang: '旁胖庞磅彷',
  pao: '跑炮泡抛袍刨咆庖',
  pei: '配培陪赔佩沛胚裴',
  pen: '盆喷',
  peng: '朋碰捧蓬棚彭澎篷怦',
  pi: '皮批披匹劈啤脾琵毗痞癖',
  pian: '片篇偏骗翩扁骈',
  piao: '票漂飘瓢嫖缥',
  pie: '撇瞥',
  pin: '品贫拼频聘姘',
  ping: '平评瓶凭屏萍苹坪',
  po: '破婆迫魄泊珀朴泼',
  pou: '剖',
  pu: '普铺朴仆蒲葡埔菩脯',
  qi: '起其气期七器奇企启乞汽旗棋歧齐泣崎祁骑岂',
  qia: '恰洽掐卡',
  qian: '前千钱签牵铅潜谦乾钳阡虔',
  qiang: '强墙抢枪腔羌蔷锵',
  qiao: '桥巧敲瞧翘乔侨荞撬鞘',
  qie: '切且怯窃茄惬',
  qin: '亲琴勤秦禽侵沁芹',
  qing: '请情清青轻庆晴倾卿氰磬',
  qiong: '穷琼穹',
  qiu: '求球秋丘囚酋泅',
  qu: '取去区曲趣驱屈躯趋渠',
  quan: '全权圈拳券泉劝颧犬蜷',
  que: '却确缺雀鹊瘸阙榷',
  qun: '群裙逡',
  ran: '然燃染冉髯',
  rang: '让嚷壤攘',
  rao: '绕饶扰娆',
  re: '热惹',
  ren: '人认任仁忍刃韧妊纫',
  ri: '日',
  rong: '容荣融戎绒溶蓉榕茸',
  rou: '肉揉柔蹂鞣',
  ru: '如入乳茹儒濡辱',
  ruan: '软阮',
  rui: '瑞锐蕊睿芮蚋',
  run: '润闰',
  ruo: '若弱偌箬',
  sa: '撒洒萨仨飒',
  sai: '塞腮赛鳃',
  san: '三散伞叁',
  sang: '桑丧嗓搡',
  sao: '扫骚嫂臊',
  se: '色涩瑟啬塞',
  sen: '森',
  seng: '僧',
  sha: '杀沙纱傻啥莎砂煞杉',
  shai: '晒筛色',
  shan: '山闪善单衫扇煽珊删赡苫膳',
  shang: '上商伤赏尚裳墒',
  shao: '少烧稍邵勺梢捎鞘苕',
  she: '社射设蛇舌舍摄涉赦慑麝',
  shei: '谁',
  shen: '深身神什审伸申渗绅婶甚肾',
  sheng: '生声省胜升盛绳圣剩甥笙',
  shi: '是时事十世实使市师式试识诗石食施拾湿尸失释史士氏驶',
  shou: '手受收首授售守瘦寿兽狩绶',
  shu: '书数树输叔术熟梳殊舒疏淑抒枢束',
  shua: '刷耍',
  shuai: '帅摔衰甩率',
  shuan: '栓拴涮',
  shuang: '双爽霜',
  shui: '水睡谁税',
  shun: '顺舜瞬',
  shuo: '说硕朔烁',
  si: '四死思司丝似私撕嘶斯厮饲祀肆',
  song: '送松宋诵颂嵩凇',
  sou: '搜艘擞嗽叟薮',
  su: '苏速素诉俗塑肃宿粟夙',
  suan: '算酸蒜狻',
  sui: '随岁碎遂隋绥髓祟隧',
  sun: '孙损笋榫荪',
  suo: '所锁缩索娑蓑梭',
  ta: '他她它塔踏塌拓獭沓',
  tai: '太台态胎抬泰苔钛汰',
  tan: '谈探叹弹碳摊贪滩瘫痰坛檀袒',
  tang: '堂糖汤趟唐淌躺膛塘搪棠',
  tao: '套逃淘陶涛桃讨滔韬萄',
  te: '特',
  teng: '疼腾藤滕',
  ti: '体提题替踢啼蹄梯锑涕剃惕',
  tian: '天田甜填添舔恬钿腆',
  tiao: '条跳调挑眺迢笤',
  tie: '铁贴帖帖',
  ting: '听停庭挺艇汀廷婷',
  tong: '同通统痛童铜筒彤瞳桐',
  tou: '头投透偷骰',
  tu: '土途图涂突兔秃徒屠',
  tuan: '团湍',
  tui: '推退腿颓蜕',
  tun: '吞囤臀',
  tuo: '脱拖拓妥陀驼驮舵唾',
  wa: '挖娃瓦哇袜蛙洼娲',
  wai: '外歪',
  wan: '完万晚玩弯碗丸宛婉挽皖腕纨',
  wang: '王网望忘亡往旺汪枉妄',
  wei: '为位围微卫威唯违委维喂伟胃慰韦畏苇纬',
  wen: '文问温闻吻稳纹蚊紊汶',
  weng: '翁嗡瓮',
  wo: '我握蜗沃卧斡',
  wu: '五无物午悟误武舞务雾污乌巫吴梧吾伍蜈',
  xi: '西习喜系细希洗息悉稀锡吸溪熄昔惜析膝蟋袭席',
  xia: '下夏吓虾瞎峡狭霞侠辖瑕',
  xian: '现先线县显限险鲜衔弦宪陷贤娴羡腺',
  xiang: '想向像响香乡相箱享祥湘项巷襄详翔',
  xiao: '小笑晓效消宵销萧硝嚣哮潇淆',
  xie: '些写谢鞋斜血歇协携邪胁挟蟹屑卸谐懈泄泻',
  xin: '心新信欣芯辛薪昕馨衅',
  xing: '行 Xing 兴形型星姓性刑省腥邢',
  xiong: '雄熊凶兄胸汹匈芎',
  xiu: '修休秀锈绣袖羞嗅宿朽',
  xu: '需许续序须虚叙畜旭恤蓄酗',
  xuan: '选宣悬旋玄渲轩喧炫眩',
  xue: '学雪血靴穴噱',
  xun: '寻训讯迅巡循勋询荀熏',
  ya: '压呀牙亚押芽鸭哑鸦雅涯衙',
  yan: '眼言研颜严岩沿延验烟厌宴演艳堰咽燕',
  yang: '样养阳扬洋仰杨殃痒央漾鸯',
  yao: '要药摇咬腰邀遥窑瑶尧谣耀',
  ye: '也夜叶业爷野页冶液耶椰咽掖',
  yi: '一已以意医衣易依仪宜移益遗义艺议异译忆抑翼',
  yin: '因音引银印阴饮隐姻殷吟尹寅',
  ying: '应英影营映迎盈赢颖蝇樱鹰萦嬴',
  yong: '用永勇拥涌咏泳雍恿蛹壅',
  you: '有又友游优尤由右诱幼幽悠邮犹佑油酉',
  yu: '与于雨鱼语欲予娱余渔愉逾隅愚榆渝虞',
  yuan: '元原员远圆院源愿缘园袁援鸳冤垣猿辕',
  yue: '月乐越约阅跃岳悦曰粤',
  yun: '云运允孕韵蕴酝耘匀陨',
  za: '杂砸咋匝',
  zai: '在再载灾栽宰哉',
  zan: '咱暂攒赞簪',
  zang: '脏葬藏臧',
  zao: '早造遭糟枣灶凿躁藻皂',
  ze: '则责择泽啧仄',
  zei: '贼',
  zen: '怎谮',
  zeng: '曾增赠憎缯',
  zha: '扎炸渣咋查眨榨闸诈咤',
  zhai: '摘宅窄债斋翟',
  zhan: '站战占展沾斩绽湛毡瞻栈',
  zhang: '张章涨掌丈仗帐胀账瘴杖蟑',
  zhao: '找照招召罩赵爪昭沼兆肇',
  zhe: '这着者者折哲浙辙蔗蛰',
  zhen: '真针镇阵震珍诊振圳桢甄',
  zheng: '正整政证征争郑挣睁筝峥',
  zhi: '之只知直支指纸职止制志质织执智治植值置脂旨至枝址趾',
  zhong: '中种重钟众忠终仲肿衷冢',
  zhou: '周州洲粥轴皱宙骤帚咒肘',
  zhu: '主住注猪竹助著祝驻铸筑珠株朱逐蛛烛瞩',
  zhua: '抓爪',
  zhuai: '拽转',
  zhuan: '转专赚砖传篆撰',
  zhuang: '装撞壮状庄桩妆',
  zhui: '追坠缀锥赘惴',
  zhun: '准谆肫',
  zhuo: '着桌捉灼浊卓琢茁酌濯',
  zi: '子自字紫资姿兹滋淄孜姊梓咨',
  zong: '总宗踪棕综纵鬃',
  zou: '走揍邹奏',
  zu: '族足组阻祖租卒诅',
  zuan: '钻躜纂攥',
  zui: '最罪醉嘴',
  zun: '尊遵樽鳟',
  zuo: '做作左坐昨佐琢',
}

function charToPinyin(char) {
  if (!char) return ''
  for (const [pinyin, chars] of Object.entries(PINYIN_DICT)) {
    if (chars.includes(char)) {
      return pinyin
    }
  }
  return char
}

function getPinyinInitials(text) {
  if (!text || typeof text !== 'string') return ''
  return text
    .split('')
    .map((char) => {
      const pinyin = charToPinyin(char)
      return pinyin[0] || char
    })
    .join('')
}

function getPinyinFull(text) {
  if (!text || typeof text !== 'string') return ''
  return text
    .split('')
    .map((char) => charToPinyin(char))
    .join('')
}

function getSearchVariants(text) {
  if (!text) return { original: '', initials: '', full: '' }
  const lower = text.toLowerCase()
  return {
    original: lower,
    initials: getPinyinInitials(lower),
    full: getPinyinFull(lower),
  }
}

function matchFuzzy(text, query) {
  if (!text || !query) return false
  const textVariants = getSearchVariants(text)
  const queryLower = query.toLowerCase()

  if (textVariants.original.includes(queryLower)) return true
  if (textVariants.initials.includes(queryLower)) return true
  if (textVariants.full.includes(queryLower)) return true

  const queryVariants = getSearchVariants(query)
  if (textVariants.original.includes(queryVariants.initials)) return true
  if (textVariants.original.includes(queryVariants.full)) return true

  return false
}

function calculateFuzzyScore(text, query) {
  if (!text || !query) return 0
  const textLower = text.toLowerCase()
  const queryLower = query.toLowerCase()

  if (textLower === queryLower) return 100
  if (textLower.startsWith(queryLower)) return 90

  const textVariants = getSearchVariants(text)
  const queryVariants = getSearchVariants(query)

  if (textVariants.original.includes(queryLower)) {
    const index = textVariants.original.indexOf(queryLower)
    return 80 - index
  }

  if (textVariants.initials === queryVariants.initials) return 70
  if (textVariants.initials.startsWith(queryVariants.initials)) return 65
  if (textVariants.initials.includes(queryVariants.initials)) return 60

  if (textVariants.full.includes(queryVariants.original)) return 50
  if (textVariants.full.includes(queryVariants.full)) return 45
  if (textVariants.original.includes(queryVariants.full)) return 40

  return 0
}

export {
  PINYIN_DICT,
  charToPinyin,
  getPinyinInitials,
  getPinyinFull,
  getSearchVariants,
  matchFuzzy,
  calculateFuzzyScore,
}
