const VERSION = '1.0.0'

const ERROR_CODES = {
  INVALID_EVENT_NAME: 'INVALID_EVENT_NAME',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  MAX_LISTENERS_EXCEEDED: 'MAX_LISTENERS_EXCEEDED',
  CIRCULAR_EMIT_DETECTED: 'CIRCULAR_EMIT_DETECTED',
  NON_SERIALIZABLE_PAYLOAD: 'NON_SERIALIZABLE_PAYLOAD',
  SUBSCRIBER_ERROR: 'SUBSCRIBER_ERROR',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_EVENT_NAME]: '无效的事件名称',
  [ERROR_CODES.INVALID_PAYLOAD]: '无效的事件载荷',
  [ERROR_CODES.MAX_LISTENERS_EXCEEDED]: '超出最大监听数限制',
  [ERROR_CODES.CIRCULAR_EMIT_DETECTED]: '检测到循环 emit 调用',
  [ERROR_CODES.NON_SERIALIZABLE_PAYLOAD]: '载荷包含不可序列化类型',
  [ERROR_CODES.SUBSCRIBER_ERROR]: '订阅者回调执行错误',
}

const DEFAULT_MAX_LISTENERS_PER_EVENT = 10

const DEFAULT_LOG_BUFFER_SIZE = 1000

const DEFAULT_CIRCULAR_EMIT_THRESHOLD = 10

const DEFAULT_MERGE_WINDOW_MS = 16

const OVERFLOW_STRATEGIES = {
  DROP_OLDEST: 'drop_oldest',
  REJECT_NEW: 'reject_new',
}

const NAMESPACE_SEPARATOR = ':'

const WILDCARD = '*'

export {
  VERSION,
  ERROR_CODES,
  ERROR_MESSAGES,
  DEFAULT_MAX_LISTENERS_PER_EVENT,
  DEFAULT_LOG_BUFFER_SIZE,
  DEFAULT_CIRCULAR_EMIT_THRESHOLD,
  DEFAULT_MERGE_WINDOW_MS,
  OVERFLOW_STRATEGIES,
  NAMESPACE_SEPARATOR,
  WILDCARD,
}
