const ERROR_CODES = {
  NULL_INPUT: 'NULL_INPUT',
  INPUT_TOO_LARGE: 'INPUT_TOO_LARGE',
  TOO_MANY_ROWS: 'TOO_MANY_ROWS',
  TOO_MANY_COLS: 'TOO_MANY_COLS',
  CELL_TOO_LARGE: 'CELL_TOO_LARGE',
  UNTERMINATED_QUOTE: 'UNTERMINATED_QUOTE',
  INCONSISTENT_COLS: 'INCONSISTENT_COLS',
  EMPTY_TABLE: 'EMPTY_TABLE',
  TRANSPOSE_SHAPE_INVALID: 'TRANSPOSE_SHAPE_INVALID',
  INVALID_DELIMITER: 'INVALID_DELIMITER',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.NULL_INPUT]: '输入不能为空',
  [ERROR_CODES.INPUT_TOO_LARGE]: '输入文本过大，超出处理限制',
  [ERROR_CODES.TOO_MANY_ROWS]: '行数超出限制',
  [ERROR_CODES.TOO_MANY_COLS]: '列数超出限制',
  [ERROR_CODES.CELL_TOO_LARGE]: '单元格内容过大，超出字节限制',
  [ERROR_CODES.UNTERMINATED_QUOTE]: '引号未闭合',
  [ERROR_CODES.INCONSISTENT_COLS]: '列数不一致',
  [ERROR_CODES.EMPTY_TABLE]: '表格为空',
  [ERROR_CODES.TRANSPOSE_SHAPE_INVALID]: '转置时表格形状无效',
  [ERROR_CODES.INVALID_DELIMITER]: '无效的分隔符',
}

const MAX_ROWS = 10000
const MAX_COLS = 1000
const MAX_CELL_BYTES = 64 * 1024
const MAX_INPUT_BYTES = 50 * 1024 * 1024

function createError(code, details = null) {
  return {
    code,
    message: ERROR_MESSAGES[code] || '未知错误',
    details,
  }
}

function getErrorMessage(code) {
  return ERROR_MESSAGES[code] || '未知错误'
}

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  MAX_ROWS,
  MAX_COLS,
  MAX_CELL_BYTES,
  MAX_INPUT_BYTES,
  createError,
  getErrorMessage,
}
