const ERROR_CODES = {
  EMPTY_INPUT: 'EMPTY_INPUT',
  INVALID_FORMAT: 'INVALID_FORMAT',
  EXTENSION_NOT_ALLOWED: 'EXTENSION_NOT_ALLOWED',
  MIME_CONFLICT: 'MIME_CONFLICT',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  TOTAL_SIZE_EXCEEDED: 'TOTAL_SIZE_EXCEEDED',
  FILE_COUNT_EXCEEDED: 'FILE_COUNT_EXCEEDED',
  FILE_READ_ERROR: 'FILE_READ_ERROR',
  EMPTY_FILE: 'EMPTY_FILE',
  DIRECTORY_NOT_SUPPORTED: 'DIRECTORY_NOT_SUPPORTED',
  NON_UTF8_FILENAME: 'NON_UTF8_FILENAME',
  CLIPBOARD_READ_ERROR: 'CLIPBOARD_READ_ERROR',
  UPLOAD_PREPARE_ERROR: 'UPLOAD_PREPARE_ERROR',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.EMPTY_INPUT]: '输入不能为空',
  [ERROR_CODES.INVALID_FORMAT]: '输入格式无效',
  [ERROR_CODES.EXTENSION_NOT_ALLOWED]: '文件扩展名不在白名单中',
  [ERROR_CODES.MIME_CONFLICT]: '声明的文件类型与实际文件头不一致',
  [ERROR_CODES.FILE_SIZE_EXCEEDED]: '单个文件大小超出上限',
  [ERROR_CODES.TOTAL_SIZE_EXCEEDED]: '总文件大小超出上限',
  [ERROR_CODES.FILE_COUNT_EXCEEDED]: '文件数量超出上限',
  [ERROR_CODES.FILE_READ_ERROR]: '无法读取文件',
  [ERROR_CODES.EMPTY_FILE]: '文件为空',
  [ERROR_CODES.DIRECTORY_NOT_SUPPORTED]: '当前环境不支持目录拖拽',
  [ERROR_CODES.NON_UTF8_FILENAME]: '文件名可能包含非 UTF-8 字符',
  [ERROR_CODES.CLIPBOARD_READ_ERROR]: '无法读取剪贴板内容',
  [ERROR_CODES.UPLOAD_PREPARE_ERROR]: '上传准备失败',
}

const RECOVERY_HINTS = {
  [ERROR_CODES.EXTENSION_NOT_ALLOWED]: '请检查文件扩展名是否正确，或使用允许的类型后重试',
  [ERROR_CODES.MIME_CONFLICT]: '文件可能被篡改或扩展名被修改，请确认文件来源',
  [ERROR_CODES.FILE_SIZE_EXCEEDED]: '请选择更小的文件后重试',
  [ERROR_CODES.TOTAL_SIZE_EXCEEDED]: '请减少文件数量或选择更小的文件后重试',
  [ERROR_CODES.FILE_COUNT_EXCEEDED]: '请减少文件数量后重试',
  [ERROR_CODES.DIRECTORY_NOT_SUPPORTED]: '请逐个拖拽文件而非目录，或使用文件选择器',
  [ERROR_CODES.CLIPBOARD_READ_ERROR]: '请检查浏览器是否允许剪贴板访问权限',
}

const MATCH_STATES = {
  MATCH: 'match',
  CONFLICT: 'conflict',
  UNKNOWN: 'unknown',
}

const DRAG_STATES = {
  IDLE: 'idle',
  DRAGGING_OVER: 'dragging_over',
}

const READ_MODES = {
  VALIDATE_ONLY: 'validate_only',
  READ_CONTENT: 'read_content',
}

const DEFAULT_MAX_FILES = 10
const DEFAULT_MAX_SINGLE_FILE_SIZE = 50 * 1024 * 1024
const DEFAULT_MAX_TOTAL_SIZE = 200 * 1024 * 1024
const DEFAULT_ALLOW_EMPTY_FILE = false
const DEFAULT_PARTIAL_PASS = true
const DEFAULT_READ_CHUNK_SIZE = 64 * 1024

const ALLOWED_EXTENSIONS_DEFAULT = new Set([
  'txt', 'md', 'json', 'xml', 'html', 'htm', 'css', 'js', 'mjs',
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'avif', 'svg',
  'pdf',
  'csv',
  'zip',
])

const MAX_FILE_HEADER_BYTES = 512

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  RECOVERY_HINTS,
  MATCH_STATES,
  DRAG_STATES,
  READ_MODES,
  DEFAULT_MAX_FILES,
  DEFAULT_MAX_SINGLE_FILE_SIZE,
  DEFAULT_MAX_TOTAL_SIZE,
  DEFAULT_ALLOW_EMPTY_FILE,
  DEFAULT_PARTIAL_PASS,
  DEFAULT_READ_CHUNK_SIZE,
  ALLOWED_EXTENSIONS_DEFAULT,
  MAX_FILE_HEADER_BYTES,
}
