import {
  ERROR_CODES,
  ERROR_MESSAGES,
  RECOVERY_HINTS,
  MATCH_STATES,
  DRAG_STATES,
  READ_MODES,
  DEFAULT_MAX_FILES,
  DEFAULT_MAX_SINGLE_FILE_SIZE,
  DEFAULT_MAX_TOTAL_SIZE,
  DEFAULT_ALLOW_EMPTY_FILE,
  DEFAULT_PARTIAL_PASS,
  DEFAULT_READ_CHUNK_SIZE,
  ALLOWED_EXTENSIONS_DEFAULT,
  MAX_FILE_HEADER_BYTES,
} from './constants.js'

import {
  getErrorMessage,
  getRecoveryHint,
  createError,
  createDiagnostic,
  isValidErrorCode,
} from './errors.js'

import {
  CATEGORIES,
  MIME_TABLE,
  MAGIC_NUMBERS,
  MIME_TO_EXTENSION,
  IMAGE_MIMES,
  TEXT_BASED_MIMES,
  buildExtensionIndex,
  buildMimeIndex,
  normalizeExtension,
  normalizeMime,
  getExtensionForMime,
  getExtensionForMimeOrDefault,
  suggestFilenameFromMime,
  isTextBasedMime,
  isImageMime,
  getExtensionFromFilename,
  formatSize,
} from './mimeData.js'

import {
  matchesSignature,
  inferMimeTypeFromBytes,
  readFileHeader,
  checkMagicNumberForFile,
  compareWithExtension,
  bytesToHexString,
} from './magicNumbers.js'

import {
  DEFAULT_OPTIONS,
  validateOptions,
  validateExtension,
  validateSingleFileSize,
  validateEmptyFile,
  validateFileCount,
  validateTotalSize,
  validateMagicNumber,
  validateSingleFile,
  validateFiles,
  prepareUpload,
} from './validation.js'

import {
  createDragStateMachine,
  extractFilesFromDataTransfer,
  readClipboardFiles,
  deduplicateFilenames,
  buildDownloadDescriptor,
  buildDownloadDescriptors,
  readFileWithProgress,
  readFilesWithProgress,
  isNonUtf8Filename,
  createFileListFromFiles,
} from './fileHandling.js'

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  RECOVERY_HINTS,
  MATCH_STATES,
  DRAG_STATES,
  READ_MODES,
  DEFAULT_MAX_FILES,
  DEFAULT_MAX_SINGLE_FILE_SIZE,
  DEFAULT_MAX_TOTAL_SIZE,
  DEFAULT_ALLOW_EMPTY_FILE,
  DEFAULT_PARTIAL_PASS,
  DEFAULT_READ_CHUNK_SIZE,
  ALLOWED_EXTENSIONS_DEFAULT,
  MAX_FILE_HEADER_BYTES,

  getErrorMessage,
  getRecoveryHint,
  createError,
  createDiagnostic,
  isValidErrorCode,

  CATEGORIES,
  MIME_TABLE,
  MAGIC_NUMBERS,
  MIME_TO_EXTENSION,
  IMAGE_MIMES,
  TEXT_BASED_MIMES,
  buildExtensionIndex,
  buildMimeIndex,
  normalizeExtension,
  normalizeMime,
  getExtensionForMime,
  getExtensionForMimeOrDefault,
  suggestFilenameFromMime,
  isTextBasedMime,
  isImageMime,
  getExtensionFromFilename,
  formatSize,

  matchesSignature,
  inferMimeTypeFromBytes,
  readFileHeader,
  checkMagicNumberForFile,
  compareWithExtension,
  bytesToHexString,

  DEFAULT_OPTIONS,
  validateOptions,
  validateExtension,
  validateSingleFileSize,
  validateEmptyFile,
  validateFileCount,
  validateTotalSize,
  validateMagicNumber,
  validateSingleFile,
  validateFiles,
  prepareUpload,

  createDragStateMachine,
  extractFilesFromDataTransfer,
  readClipboardFiles,
  deduplicateFilenames,
  buildDownloadDescriptor,
  buildDownloadDescriptors,
  readFileWithProgress,
  readFilesWithProgress,
  isNonUtf8Filename,
  createFileListFromFiles,
}
