import { WARNING_LEVEL } from './constants.js'

const ERROR_CODES = {
  EMPTY_INPUT: 'EMPTY_INPUT',
  EMPTY_SEGMENT: 'EMPTY_SEGMENT',
  WHITESPACE_ONLY: 'WHITESPACE_ONLY',
  TOO_MANY_SEGMENTS: 'TOO_MANY_SEGMENTS',
  SEGMENT_TOO_LONG: 'SEGMENT_TOO_LONG',
  TOTAL_TOO_LONG: 'TOTAL_TOO_LONG',
  TOO_MANY_LINES: 'TOO_MANY_LINES',
  TRAVERSAL_DETECTED: 'TRAVERSAL_DETECTED',
  DANGEROUS_SCHEME: 'DANGEROUS_SCHEME',
  WINDOWS_RESERVED_NAME: 'WINDOWS_RESERVED_NAME',
  INVALID_URL: 'INVALID_URL',
  INVALID_WINDOWS_PATH: 'INVALID_WINDOWS_PATH',
  SUSPICIOUS_UNC_PREFIX: 'SUSPICIOUS_UNC_PREFIX',
  SUSPICIOUS_DRIVE_LETTER: 'SUSPICIOUS_DRIVE_LETTER',
  INVALID_OPTION: 'INVALID_OPTION',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.EMPTY_INPUT]: '输入为空',
  [ERROR_CODES.EMPTY_SEGMENT]: '包含空片段',
  [ERROR_CODES.WHITESPACE_ONLY]: '输入仅包含空白字符',
  [ERROR_CODES.TOO_MANY_SEGMENTS]: '片段数量超出安全上限',
  [ERROR_CODES.SEGMENT_TOO_LONG]: '单段长度超出安全上限',
  [ERROR_CODES.TOTAL_TOO_LONG]: '合并总长度超出安全上限',
  [ERROR_CODES.TOO_MANY_LINES]: '批量行数超出安全上限',
  [ERROR_CODES.TRAVERSAL_DETECTED]: '检测到路径穿越 (..)，已拒绝输出',
  [ERROR_CODES.DANGEROUS_SCHEME]: '检测到危险 scheme',
  [ERROR_CODES.WINDOWS_RESERVED_NAME]: '包含 Windows 保留设备名',
  [ERROR_CODES.INVALID_URL]: '无效的 URL 格式',
  [ERROR_CODES.INVALID_WINDOWS_PATH]: '无效的 Windows 路径格式',
  [ERROR_CODES.SUSPICIOUS_UNC_PREFIX]: '检测到可疑的 UNC 前缀',
  [ERROR_CODES.SUSPICIOUS_DRIVE_LETTER]: '检测到可疑的盘符',
  [ERROR_CODES.INVALID_OPTION]: '无效的配置选项',
}

function createError(code, details = null, level = WARNING_LEVEL.ERROR) {
  return {
    code,
    message: ERROR_MESSAGES[code] || '未知错误',
    details,
    level,
  }
}

function createWarning(code, details = null, level = WARNING_LEVEL.WARNING) {
  return {
    code,
    message: ERROR_MESSAGES[code] || '未知警告',
    details,
    level,
  }
}

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  createError,
  createWarning,
}
