const ERROR_CODES = {
  EMPTY_INPUT: 'EMPTY_INPUT',
  INPUT_TOO_LARGE: 'INPUT_TOO_LARGE',
  TOO_MANY_LINES: 'TOO_MANY_LINES',
  LINE_TOO_LONG: 'LINE_TOO_LONG',
  INVALID_SEMVER: 'INVALID_SEMVER',
  INVALID_VERSION_SEGMENT: 'INVALID_VERSION_SEGMENT',
  VERSION_NUMBER_TOO_LARGE: 'VERSION_NUMBER_TOO_LARGE',
  EMPTY_VERSION_SEGMENT: 'EMPTY_VERSION_SEGMENT',
  INVALID_PRERELEASE: 'INVALID_PRERELEASE',
  INVALID_BUILD_METADATA: 'INVALID_BUILD_METADATA',
  INVALID_RANGE: 'INVALID_RANGE',
  MIXED_INVALID_LINES: 'MIXED_INVALID_LINES',
}

const MAX_SAFE_INPUT_SIZE = 10 * 1024 * 1024
const MAX_LINE_COUNT = 5000
const MAX_LINE_LENGTH = 4096
const MAX_SAFE_INTEGER = 9007199254740991
const LARGE_LIST_THRESHOLD = 500

const ERROR_MESSAGES = {
  [ERROR_CODES.EMPTY_INPUT]: '输入内容为空',
  [ERROR_CODES.INPUT_TOO_LARGE]: '输入内容超过大小限制',
  [ERROR_CODES.TOO_MANY_LINES]: '行数超过限制',
  [ERROR_CODES.LINE_TOO_LONG]: '单行内容过长',
  [ERROR_CODES.INVALID_SEMVER]: '无效的语义化版本',
  [ERROR_CODES.INVALID_VERSION_SEGMENT]: '无效的版本段',
  [ERROR_CODES.VERSION_NUMBER_TOO_LARGE]: '版本号超出安全范围',
  [ERROR_CODES.EMPTY_VERSION_SEGMENT]: '版本段不能为空',
  [ERROR_CODES.INVALID_PRERELEASE]: '无效的先行版标识',
  [ERROR_CODES.INVALID_BUILD_METADATA]: '无效的构建元数据',
  [ERROR_CODES.INVALID_RANGE]: '无效的范围表达式',
  [ERROR_CODES.MIXED_INVALID_LINES]: '存在非法行',
}

function createError(errorCode, details = {}) {
  return {
    code: errorCode,
    message: ERROR_MESSAGES[errorCode] || '未知错误',
    details,
  }
}

export {
  ERROR_CODES,
  MAX_SAFE_INPUT_SIZE,
  MAX_LINE_COUNT,
  MAX_LINE_LENGTH,
  MAX_SAFE_INTEGER,
  LARGE_LIST_THRESHOLD,
  ERROR_MESSAGES,
  createError,
}
