const ERROR_CODES = {
  EMPTY_INPUT: 'EMPTY_INPUT',
  INPUT_TOO_LARGE: 'INPUT_TOO_LARGE',
  TOO_MANY_ITEMS: 'TOO_MANY_ITEMS',
  INVALID_TEMPLATE: 'INVALID_TEMPLATE',
  CIRCULAR_REFERENCE: 'CIRCULAR_REFERENCE',
  MISSING_PLACEHOLDER: 'MISSING_PLACEHOLDER',
  INVALID_VERSION: 'INVALID_VERSION',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  INVALID_SCOPE: 'INVALID_SCOPE',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.EMPTY_INPUT]: '输入为空，请提供必要内容',
  [ERROR_CODES.INPUT_TOO_LARGE]: '输入内容过大，超出安全上限',
  [ERROR_CODES.TOO_MANY_ITEMS]: '条目数量超出上限',
  [ERROR_CODES.INVALID_TEMPLATE]: '模板语法错误',
  [ERROR_CODES.CIRCULAR_REFERENCE]: '模板存在循环引用的占位符',
  [ERROR_CODES.MISSING_PLACEHOLDER]: '存在未填充的占位符',
  [ERROR_CODES.INVALID_VERSION]: '版本号格式错误，不符合 SemVer 规范',
  [ERROR_CODES.INVALID_DATE_FORMAT]: '日期格式无效',
  [ERROR_CODES.INVALID_SCOPE]: 'Scope 格式无效',
}

const MAX_SAFE_ITEMS = 1000
const MAX_SAFE_OUTPUT_SIZE = 2 * 1024 * 1024
const MAX_PLACEHOLDER_DEPTH = 20
const LARGE_TEXT_THRESHOLD = 100 * 1024
const LOCAL_STORAGE_KEY = 'changelog-draft-builder:v1'

function createError(code, details = null) {
  return {
    code,
    message: ERROR_MESSAGES[code] || '未知错误',
    details,
  }
}

export {
    ERROR_CODES,
    ERROR_MESSAGES, LARGE_TEXT_THRESHOLD,
    LOCAL_STORAGE_KEY, MAX_PLACEHOLDER_DEPTH, MAX_SAFE_ITEMS,
    MAX_SAFE_OUTPUT_SIZE, createError
}

