const HISTORY_MODES = {
  PUSH: 'push',
  REPLACE: 'replace',
}

const URL_LIMITS = {
  MAX_TOTAL_LENGTH: 2048,
  MAX_QUERY_STRING_LENGTH: 2000,
  KEY_REGEX: /^[a-zA-Z_][a-zA-Z0-9_]*(\[[a-zA-Z0-9_]+\])*$/,
}

const WARNING_CODES = {
  INVALID_PARAM: 'INVALID_PARAM',
  INVALID_PERCENT_SEQUENCE: 'INVALID_PERCENT_SEQUENCE',
  INVALID_BOOLEAN: 'INVALID_BOOLEAN',
  INVALID_NUMBER: 'INVALID_NUMBER',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
  INVALID_KEY_FORMAT: 'INVALID_KEY_FORMAT',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
  VALUE_TRUNCATED: 'VALUE_TRUNCATED',
  URL_LENGTH_EXCEEDED: 'URL_LENGTH_EXCEEDED',
  HISTORY_API_UNAVAILABLE: 'HISTORY_API_UNAVAILABLE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  HISTORY_PUSH_THRESHOLD_EXCEEDED: 'HISTORY_PUSH_THRESHOLD_EXCEEDED',
}

const ERROR_CODES = {
  FILE_FIELD_NOT_ALLOWED: 'FILE_FIELD_NOT_ALLOWED',
  BLOB_FIELD_NOT_ALLOWED: 'BLOB_FIELD_NOT_ALLOWED',
  URL_LENGTH_EXCEEDED: 'URL_LENGTH_EXCEEDED',
  INVALID_SCHEMA: 'INVALID_SCHEMA',
  SYNC_LOCKED: 'SYNC_LOCKED',
}

const BOOLEAN_TRUE_STRINGS = ['true', '1', 'yes', 'on']
const BOOLEAN_FALSE_STRINGS = ['false', '0', 'no', 'off']

const DEFAULT_DEBOUNCE_MS = 300

const HISTORY_PUSH_THRESHOLD = 10

const SCHEMA_TYPES = {
  STRING: 'string',
  NUMBER: 'number',
  BOOLEAN: 'boolean',
  ENUM: 'enum',
  ARRAY: 'array',
  OBJECT: 'object',
  DATE: 'date',
}

export {
    BOOLEAN_FALSE_STRINGS, BOOLEAN_TRUE_STRINGS, DEFAULT_DEBOUNCE_MS, ERROR_CODES, HISTORY_MODES, HISTORY_PUSH_THRESHOLD,
    SCHEMA_TYPES, URL_LIMITS,
    WARNING_CODES
}

