const VERSION = '1.0.0'

const WORKER_PROTOCOL_VERSION = 1

const ENCODING_MODES = {
  UTF_16: 'utf-16',
  UTF_8: 'utf-8',
}

const WORKER_DECISION_REASONS = {
  SSS_SMALL_PAYLOAD: 'small-payload',
  SS_NO_WORKER_SUPPORT: 'no-worker-support',
  SSS_SINGLE_CORE: 'single-core',
  SSS_SHARED_BUFFER_AVAILABLE: 'shared-buffer-available',
  LARGE_PAYLOAD_MULTICORE: 'large-payload-multicore',
  THRESHOLD_BORDERLINE: 'threshold-borderline',
}

const DEFAULT_CONFIG = {
  CHUNK_SIZE_UTF16: 16 * 1024,
  CHUNK_SIZE_UTF8: 32 * 1024,
  DEBOUNCE_WAIT_MS: 100,
  DEBOUNCE_MAX_WAIT_MS: 500,
  WORKER_THRESHOLD_BYTES: 512 * 1024,
  WORKER_HARDWARE_MIN_CORES: 2,
  VIRTUAL_LIST_DEFAULT_ITEM_HEIGHT: 40,
  VIRTUAL_LIST_OVERSCAN_COUNT: 5,
  VIRTUAL_LIST_FAST_SCROLL_THRESHOLD_PX: 100,
  MESSAGE_QUEUE_MAX_DEPTH: 100,
  TEXT_ENCODER_MAX_BYTES_PER_CALL: 100 * 1024 * 1024,
  DATASET_SIZES: {
    small: 100,
    medium: 5000,
    large: 100000,
  },
  FRAME_TIME_BUDGET_MS: 8,
}

const ERROR_CODES = {
  INVALID_ENCODING: 'INVALID_ENCODING',
  INVALID_CHUNK_SIZE: 'INVALID_CHUNK_SIZE',
  TEXT_TOO_LARGE: 'TEXT_TOO_LARGE',
  WORKER_CONSTRUCTION_FAILED: 'WORKER_CONSTRUCTION_FAILED',
  MESSAGE_QUEUE_OVERFLOW: 'MESSAGE_QUEUE_OVERFLOW',
  INVALID_WORKER_MESSAGE: 'INVALID_WORKER_MESSAGE',
  WORKER_PROTOCOL_MISMATCH: 'WORKER_PROTOCOL_MISMATCH',
  DOM_ACCESS_IN_WORKER: 'DOM_ACCESS_IN_WORKER',
  CANCELLED: 'CANCELLED',
  INVALID_EDITOR_REF: 'INVALID_EDITOR_REF',
  UNKNOWN: 'UNKNOWN',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_ENCODING]: '无效的编码模式',
  [ERROR_CODES.INVALID_CHUNK_SIZE]: '无效的分片大小',
  [ERROR_CODES.TEXT_TOO_LARGE]: '文本超出单次编码限制',
  [ERROR_CODES.WORKER_CONSTRUCTION_FAILED]: 'Worker 构造失败',
  [ERROR_CODES.MESSAGE_QUEUE_OVERFLOW]: '消息队列溢出',
  [ERROR_CODES.INVALID_WORKER_MESSAGE]: '无效的 Worker 消息',
  [ERROR_CODES.WORKER_PROTOCOL_MISMATCH]: 'Worker 协议版本不匹配',
  [ERROR_CODES.DOM_ACCESS_IN_WORKER]: 'Worker 内禁止 DOM 访问',
  [ERROR_CODES.CANCELLED]: '操作已取消',
  [ERROR_CODES.INVALID_EDITOR_REF]: '无效的编辑器引用',
  [ERROR_CODES.UNKNOWN]: '未知错误',
}

const WORKER_MESSAGE_TYPES = {
  INIT: 'init',
  PROCESS_TEXT: 'process-text',
  PROCESS_RESULT: 'process-result',
  PROGRESS: 'progress',
  ERROR: 'error',
  CANCEL: 'cancel',
  PING: 'ping',
  PONG: 'pong',
}

const SSR_SAFE_EXPORTS = [
  'createTextChunkIterator',
  'createDebouncedFn',
  'estimateMemoryUsage',
  'calculateVisibleRange',
  'VERSION',
  'ENCODING_MODES',
  'ERROR_CODES',
]

export {
  VERSION,
  WORKER_PROTOCOL_VERSION,
  ENCODING_MODES,
  WORKER_DECISION_REASONS,
  DEFAULT_CONFIG,
  ERROR_CODES,
  ERROR_MESSAGES,
  WORKER_MESSAGE_TYPES,
  SSR_SAFE_EXPORTS,
}
