import {
  levenshteinDistance,
  bitapScore,
  normalizeText,
  generateNgrams,
  tokenize,
  mergeRanges,
  findMatchRanges,
  calculateFuzzyScore,
  buildFuzzyIndex,
  searchFuzzy,
} from './core.js'
import {
  MAX_EDIT_DISTANCE,
  NGRAM_SIZE,
  DEFAULT_LIMIT,
  MAX_INDEX_ENTRIES,
  DEBOUNCE_DEFAULT,
  WORKER_THRESHOLD,
  MAX_HISTORY_SIZE,
  MIN_QUERY_LENGTH,
  CONTINUITY_BONUS,
  PREFIX_BONUS,
  ASCII_FOLDING_MAP,
  STOPWORDS_DEFAULT,
  WORKER_MESSAGE_TYPES,
  ERROR_CODES,
} from './constants.js'
import {
  FuzzySearchError,
  createError,
  wrapError,
  isFuzzySearchError,
} from './errors.js'

export {
  levenshteinDistance,
  bitapScore,
  normalizeText,
  generateNgrams,
  tokenize,
  mergeRanges,
  findMatchRanges,
  calculateFuzzyScore,
  buildFuzzyIndex,
  searchFuzzy,
  MAX_EDIT_DISTANCE,
  NGRAM_SIZE,
  DEFAULT_LIMIT,
  MAX_INDEX_ENTRIES,
  DEBOUNCE_DEFAULT,
  WORKER_THRESHOLD,
  MAX_HISTORY_SIZE,
  MIN_QUERY_LENGTH,
  CONTINUITY_BONUS,
  PREFIX_BONUS,
  ASCII_FOLDING_MAP,
  STOPWORDS_DEFAULT,
  WORKER_MESSAGE_TYPES,
  ERROR_CODES,
  FuzzySearchError,
  createError,
  wrapError,
  isFuzzySearchError,
}
