const ERROR_CODES = {
  INVALID_ALGORITHM: 'INVALID_ALGORITHM',
  INVALID_KEY_SIZE: 'INVALID_KEY_SIZE',
  INVALID_CURVE: 'INVALID_CURVE',
  INVALID_PEM_FORMAT: 'INVALID_PEM_FORMAT',
  INVALID_PEM_BEGIN: 'INVALID_PEM_BEGIN',
  INVALID_PEM_END: 'INVALID_PEM_END',
  INVALID_JWK_FORMAT: 'INVALID_JWK_FORMAT',
  INVALID_SPKI_FORMAT: 'INVALID_SPKI_FORMAT',
  KEY_GENERATION_FAILED: 'KEY_GENERATION_FAILED',
  KEY_EXPORT_FAILED: 'KEY_EXPORT_FAILED',
  KEY_IMPORT_FAILED: 'KEY_IMPORT_FAILED',
  FINGERPRINT_FAILED: 'FINGERPRINT_FAILED',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  EMPTY_INPUT: 'EMPTY_INPUT',
  WEB_CRYPTO_NOT_AVAILABLE: 'WEB_CRYPTO_NOT_AVAILABLE',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_ALGORITHM]: '无效的算法类型',
  [ERROR_CODES.INVALID_KEY_SIZE]: '无效的密钥长度',
  [ERROR_CODES.INVALID_CURVE]: '无效的椭圆曲线',
  [ERROR_CODES.INVALID_PEM_FORMAT]: 'PEM 格式无效',
  [ERROR_CODES.INVALID_PEM_BEGIN]: '缺少有效的 BEGIN 标记',
  [ERROR_CODES.INVALID_PEM_END]: '缺少有效的 END 标记',
  [ERROR_CODES.INVALID_JWK_FORMAT]: 'JWK 格式无效',
  [ERROR_CODES.INVALID_SPKI_FORMAT]: 'SPKI 格式无效',
  [ERROR_CODES.KEY_GENERATION_FAILED]: '密钥生成失败',
  [ERROR_CODES.KEY_EXPORT_FAILED]: '密钥导出失败',
  [ERROR_CODES.KEY_IMPORT_FAILED]: '密钥导入失败',
  [ERROR_CODES.FINGERPRINT_FAILED]: '指纹计算失败',
  [ERROR_CODES.UNSUPPORTED_OPERATION]: '不支持的操作',
  [ERROR_CODES.EMPTY_INPUT]: '输入不能为空',
  [ERROR_CODES.WEB_CRYPTO_NOT_AVAILABLE]: 'Web Crypto API 不可用',
}

function getErrorMessage(code) {
  return ERROR_MESSAGES[code] || '未知错误'
}

function createError(code, customMessage = null) {
  return {
    errorCode: code,
    errorMessage: customMessage || getErrorMessage(code),
  }
}

function isWebCryptoAvailable() {
  return typeof crypto !== 'undefined' && crypto.subtle !== 'undefined'
}

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  createError,
  isWebCryptoAvailable,
}
