export const KEY_NAMESPACE = 'devtools:';

export const STORAGE_VERSIONS = {
    V1: '1.0.0',
    V2: '2.0.0',
    LATEST: '2.0.0',
};

export const DOMAIN_PREFERENCES = {
    LAYOUT: 'layout',
    WORKSPACE: 'workspace',
    THEME: 'theme',
    TOOLS: 'tools',
};

export const MERGE_STRATEGIES = {
    SHALLOW: 'shallow',
    DEEP: 'deep',
};

export const STORAGE_TYPE = {
    LOCAL: 'localStorage',
    SESSION: 'sessionStorage',
    MEMORY: 'memory',
    NONE: 'none',
};

export const STORAGE_TYPE_MATRIX = {
    [DOMAIN_PREFERENCES.LAYOUT]: STORAGE_TYPE.LOCAL,
    [DOMAIN_PREFERENCES.WORKSPACE]: STORAGE_TYPE.SESSION,
    [DOMAIN_PREFERENCES.THEME]: STORAGE_TYPE.LOCAL,
    [DOMAIN_PREFERENCES.TOOLS]: STORAGE_TYPE.LOCAL,
};

export const ERROR_CODES = {
    STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
    QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
    INVALID_KEY: 'INVALID_KEY',
    SERIALIZATION_ERROR: 'SERIALIZATION_ERROR',
    DESERIALIZATION_ERROR: 'DESERIALIZATION_ERROR',
    MERGE_ERROR: 'MERGE_ERROR',
    MIGRATION_ERROR: 'MIGRATION_ERROR',
    MIGRATION_VERSION_TOO_HIGH: 'MIGRATION_VERSION_TOO_HIGH',
    IMPORT_CORRUPTED: 'IMPORT_CORRUPTED',
    IMPORT_INVALID_CHECKSUM: 'IMPORT_INVALID_CHECKSUM',
    IMPORT_VERSION_MISMATCH: 'IMPORT_VERSION_MISMATCH',
    IMPORT_XSS_DETECTED: 'IMPORT_XSS_DETECTED',
    LRU_EVICTION_FAILED: 'LRU_EVICTION_FAILED',
    SSR_NO_WINDOW: 'SSR_NO_WINDOW',
    PRIVACY_MODE: 'PRIVACY_MODE',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

export const ERROR_MESSAGES = {
    [ERROR_CODES.STORAGE_UNAVAILABLE]: '存储不可用，已降级到内存存储',
    [ERROR_CODES.QUOTA_EXCEEDED]: '存储空间配额已满',
    [ERROR_CODES.INVALID_KEY]: '无效的键名，必须以正确的命名空间开头',
    [ERROR_CODES.SERIALIZATION_ERROR]: '序列化失败',
    [ERROR_CODES.DESERIALIZATION_ERROR]: '反序列化失败',
    [ERROR_CODES.MERGE_ERROR]: '合并策略执行失败',
    [ERROR_CODES.MIGRATION_ERROR]: '数据迁移失败',
    [ERROR_CODES.MIGRATION_VERSION_TOO_HIGH]: '数据版本高于当前支持版本',
    [ERROR_CODES.IMPORT_CORRUPTED]: '导入的数据包已损坏',
    [ERROR_CODES.IMPORT_INVALID_CHECKSUM]: '导入的数据包校验和无效',
    [ERROR_CODES.IMPORT_VERSION_MISMATCH]: '导入的数据包版本不兼容',
    [ERROR_CODES.IMPORT_XSS_DETECTED]: '检测到潜在的 XSS 注入内容',
    [ERROR_CODES.LRU_EVICTION_FAILED]: 'LRU 键驱逐策略执行失败',
    [ERROR_CODES.SSR_NO_WINDOW]: 'SSR 环境无 window 对象',
    [ERROR_CODES.PRIVACY_MODE]: '隐私模式或第三方 Cookie 隔离导致存储不可用',
    [ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
};

export const KEY_PRIORITY = {
    [DOMAIN_PREFERENCES.LAYOUT]: 10,
    [DOMAIN_PREFERENCES.WORKSPACE]: 5,
    [DOMAIN_PREFERENCES.THEME]: 15,
    [DOMAIN_PREFERENCES.TOOLS]: 8,
};

export const DEFAULT_CHECK_ALGORITHM = 'simple';
