const LOG_LEVELS = {
  TRACE: 'trace',
  DEBUG: 'debug',
  INFO: 'info',
  WARN: 'warn',
  ERROR: 'error',
  FATAL: 'fatal',
}

const LOG_LEVEL_PRIORITY = {
  [LOG_LEVELS.TRACE]: 0,
  [LOG_LEVELS.DEBUG]: 1,
  [LOG_LEVELS.INFO]: 2,
  [LOG_LEVELS.WARN]: 3,
  [LOG_LEVELS.ERROR]: 4,
  [LOG_LEVELS.FATAL]: 5,
}

const SAMPLING_STRATEGIES = {
  HEAD_ONLY: 'head_only',
  UNIFORM: 'uniform',
  SMART_ERROR: 'smart_error',
}

const ANSI_COLORS = {
  BLACK: 30,
  RED: 31,
  GREEN: 32,
  YELLOW: 33,
  BLUE: 34,
  MAGENTA: 35,
  CYAN: 36,
  WHITE: 37,
  BRIGHT_BLACK: 90,
  BRIGHT_RED: 91,
  BRIGHT_GREEN: 92,
  BRIGHT_YELLOW: 93,
  BRIGHT_BLUE: 94,
  BRIGHT_MAGENTA: 95,
  BRIGHT_CYAN: 96,
  BRIGHT_WHITE: 97,
}

const ANSI_BG_COLORS = {
  BLACK: 40,
  RED: 41,
  GREEN: 42,
  YELLOW: 43,
  BLUE: 44,
  MAGENTA: 45,
  CYAN: 46,
  WHITE: 47,
  BRIGHT_BLACK: 100,
  BRIGHT_RED: 101,
  BRIGHT_GREEN: 102,
  BRIGHT_YELLOW: 103,
  BRIGHT_BLUE: 104,
  BRIGHT_MAGENTA: 105,
  BRIGHT_CYAN: 106,
  BRIGHT_WHITE: 107,
}

const ANSI_STYLES = {
  RESET: 0,
  BOLD: 1,
  DIM: 2,
  ITALIC: 3,
  UNDERLINE: 4,
  BLINK: 5,
  INVERSE: 7,
  HIDDEN: 8,
  STRIKETHROUGH: 9,
}

const DEFAULT_BUFFER_CAPACITY = 10000
const DEFAULT_SAMPLE_SIZE = 1000
const DEFAULT_HEAD_KEEP_COUNT = 100
const DEFAULT_ERROR_CONTEXT_LINES = 5

const ERROR_CODES = {
  INVALID_CAPACITY: 'INVALID_CAPACITY',
  BUFFER_FULL: 'BUFFER_FULL',
  INVALID_FILTER: 'INVALID_FILTER',
  INVALID_SAMPLING: 'INVALID_SAMPLING',
  ABORTED: 'ABORTED',
}

const FOLD_TYPES = {
  JSON: 'json',
  STACK_TRACE: 'stack_trace',
  NONE: 'none',
}

export {
  LOG_LEVELS,
  LOG_LEVEL_PRIORITY,
  SAMPLING_STRATEGIES,
  ANSI_COLORS,
  ANSI_BG_COLORS,
  ANSI_STYLES,
  DEFAULT_BUFFER_CAPACITY,
  DEFAULT_SAMPLE_SIZE,
  DEFAULT_HEAD_KEEP_COUNT,
  DEFAULT_ERROR_CONTEXT_LINES,
  ERROR_CODES,
  FOLD_TYPES,
}
