const ERROR_CODES = {
  NULL_INPUT: 'NULL_INPUT',
  EMPTY_VALUE: 'EMPTY_VALUE',
  INVALID_JWT_FORMAT: 'INVALID_JWT_FORMAT',
  INVALID_SEGMENT_COUNT: 'INVALID_SEGMENT_COUNT',
  BASE64URL_DECODE_ERROR: 'BASE64URL_DECODE_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_JWKS_FORMAT: 'INVALID_JWKS_FORMAT',
  NO_MATCHING_KEY: 'NO_MATCHING_KEY',
  INVALID_KEY_FORMAT: 'INVALID_KEY_FORMAT',
  UNSUPPORTED_ALGORITHM: 'UNSUPPORTED_ALGORITHM',
  SIGNATURE_VERIFICATION_FAILED: 'SIGNATURE_VERIFICATION_FAILED',
  ALGORITHM_MISMATCH: 'ALGORITHM_MISMATCH',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_NOT_YET_VALID: 'TOKEN_NOT_YET_VALID',
  ISSUER_MISMATCH: 'ISSUER_MISMATCH',
  AUDIENCE_MISMATCH: 'AUDIENCE_MISMATCH',
  CRYPTO_NOT_AVAILABLE: 'CRYPTO_NOT_AVAILABLE',
  INVALID_CLAIM_RULES: 'INVALID_CLAIM_RULES',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.NULL_INPUT]: '输入值为 null 或 undefined',
  [ERROR_CODES.EMPTY_VALUE]: '输入值为空',
  [ERROR_CODES.INVALID_JWT_FORMAT]: 'JWT 格式无效',
  [ERROR_CODES.INVALID_SEGMENT_COUNT]: 'JWT 段数无效，应为 3 段',
  [ERROR_CODES.BASE64URL_DECODE_ERROR]: 'Base64URL 解码失败',
  [ERROR_CODES.INVALID_JSON]: 'JSON 格式无效',
  [ERROR_CODES.INVALID_JWKS_FORMAT]: 'JWKS 格式无效',
  [ERROR_CODES.NO_MATCHING_KEY]: '未找到匹配的密钥',
  [ERROR_CODES.INVALID_KEY_FORMAT]: '密钥格式无效',
  [ERROR_CODES.UNSUPPORTED_ALGORITHM]: '不支持的算法',
  [ERROR_CODES.SIGNATURE_VERIFICATION_FAILED]: '签名验证失败',
  [ERROR_CODES.ALGORITHM_MISMATCH]: '算法不匹配',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期',
  [ERROR_CODES.TOKEN_NOT_YET_VALID]: '令牌尚未生效',
  [ERROR_CODES.ISSUER_MISMATCH]: '发行者不匹配',
  [ERROR_CODES.AUDIENCE_MISMATCH]: '受众不匹配',
  [ERROR_CODES.CRYPTO_NOT_AVAILABLE]: 'Web Crypto API 不可用',
  [ERROR_CODES.INVALID_CLAIM_RULES]: 'Claims 规则配置无效',
}

function getErrorMessage(code) {
  return ERROR_MESSAGES[code] || '未知错误'
}

function createError(code, customMessage = null, details = null) {
  return {
    errorCode: code,
    errorMessage: customMessage || getErrorMessage(code),
    details,
  }
}

const SUPPORTED_ALGORITHMS = ['HS256', 'HS384', 'HS512', 'RS256', 'RS384', 'RS512', 'ES256', 'ES384', 'ES512']

function isAlgorithmSupported(alg) {
  return SUPPORTED_ALGORITHMS.includes(alg)
}

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  createError,
  SUPPORTED_ALGORITHMS,
  isAlgorithmSupported,
}
