const ERROR_CODES = {
  NULL_INPUT: 'NULL_INPUT',
  CRYPTO_NOT_AVAILABLE: 'CRYPTO_NOT_AVAILABLE',
  INVALID_ALGORITHM: 'INVALID_ALGORITHM',
  INVALID_KEY: 'INVALID_KEY',
  INVALID_IV: 'INVALID_IV',
  INVALID_INPUT_FORMAT: 'INVALID_INPUT_FORMAT',
  EMPTY_PLAINTEXT: 'EMPTY_PLAINTEXT',
  EMPTY_CIPHERTEXT: 'EMPTY_CIPHERTEXT',
  TEXT_TOO_LONG: 'TEXT_TOO_LONG',
  INVALID_BASE64: 'INVALID_BASE64',
  INVALID_HEX: 'INVALID_HEX',
  KEY_LENGTH_MISMATCH: 'KEY_LENGTH_MISMATCH',
  IV_LENGTH_MISMATCH: 'IV_LENGTH_MISMATCH',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',
  TAG_MISMATCH: 'TAG_MISMATCH',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.NULL_INPUT]: '输入值为 null 或 undefined',
  [ERROR_CODES.CRYPTO_NOT_AVAILABLE]: '当前环境不支持 Web Crypto API，请使用现代浏览器',
  [ERROR_CODES.INVALID_ALGORITHM]: '不支持的算法',
  [ERROR_CODES.INVALID_KEY]: '密钥无效',
  [ERROR_CODES.INVALID_IV]: '初始化向量 (IV) 无效',
  [ERROR_CODES.INVALID_INPUT_FORMAT]: '输入格式无效',
  [ERROR_CODES.EMPTY_PLAINTEXT]: '明文不能为空',
  [ERROR_CODES.EMPTY_CIPHERTEXT]: '密文不能为空',
  [ERROR_CODES.TEXT_TOO_LONG]: '文本长度超出限制',
  [ERROR_CODES.INVALID_BASE64]: '无效的 Base64 编码',
  [ERROR_CODES.INVALID_HEX]: '无效的十六进制编码',
  [ERROR_CODES.KEY_LENGTH_MISMATCH]: '密钥长度不匹配，AES-128 需要 16 字节、AES-256 需要 32 字节',
  [ERROR_CODES.IV_LENGTH_MISMATCH]: 'IV 长度不匹配，GCM 模式需要 12 字节',
  [ERROR_CODES.ENCRYPTION_FAILED]: '加密失败',
  [ERROR_CODES.DECRYPTION_FAILED]: '解密失败',
  [ERROR_CODES.TAG_MISMATCH]: '认证标签不匹配，密文可能已被篡改',
  [ERROR_CODES.INVALID_PARAMETER]: '参数无效',
}

function getErrorMessage(code) {
  return ERROR_MESSAGES[code] || '未知错误'
}

function createError(code, customMessage = null) {
  return {
    errorCode: code,
    errorMessage: customMessage || getErrorMessage(code),
  }
}

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  createError,
}
