const EXAMPLE_UAS = {
  desktopChrome: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  desktopFirefox: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
  desktopSafari: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15',
  desktopEdge: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
  mobileSafari: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
  mobileChrome: 'Mozilla/5.0 (Linux; Android 13; SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
  mobileAndroid: 'Mozilla/5.0 (Linux; U; Android 13; zh-CN; SM-G998B Build/TP1A.220624.014) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.0.0 Mobile Safari/537.36',
  googlebot: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
  bingbot: 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
  curl: 'curl/8.1.0',
  empty: '',
  abnormal: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 [malformed][broken)extra stuff',
}

const EXAMPLE_LABELS = {
  desktopChrome: 'Chrome (桌面)',
  desktopFirefox: 'Firefox (桌面)',
  desktopSafari: 'Safari (Mac)',
  desktopEdge: 'Edge (桌面)',
  mobileSafari: 'Safari (iPhone)',
  mobileChrome: 'Chrome (Android)',
  mobileAndroid: 'Android 浏览器',
  googlebot: 'Googlebot',
  bingbot: 'Bingbot',
  curl: 'cURL',
  empty: '空字符串',
  abnormal: '异常格式',
}

const DEVICE_TYPES = {
  DESKTOP: 'desktop',
  MOBILE: 'mobile',
  TABLET: 'tablet',
  BOT: 'bot',
  UNKNOWN: 'unknown',
}

const BROWSER_PATTERNS = [
  { name: 'Edge', pattern: /Edg\/(\d+\.?\d*)/i },
  { name: 'Edge', pattern: /Edge\/(\d+\.?\d*)/i },
  { name: 'Samsung Internet', pattern: /SamsungBrowser\/(\d+\.?\d*)/i },
  { name: 'Opera', pattern: /OPR\/(\d+\.?\d*)/i },
  { name: 'Opera', pattern: /Opera\/(\d+\.?\d*)/i },
  { name: 'Firefox', pattern: /Firefox\/(\d+\.?\d*)/i },
  { name: 'Firefox', pattern: /FxiOS\/(\d+\.?\d*)/i },
  { name: 'Chrome', pattern: /Chrome\/(\d+\.?\d*)/i },
  { name: 'Chrome', pattern: /CriOS\/(\d+\.?\d*)/i },
  { name: 'Safari', pattern: /Version\/(\d+\.?\d*).*Safari/i },
  { name: 'Safari', pattern: /Safari\/(\d+\.?\d*)/i },
  { name: 'UC Browser', pattern: /UCBrowser\/(\d+\.?\d*)/i },
  { name: 'Yandex', pattern: /YaBrowser\/(\d+\.?\d*)/i },
  { name: 'Brave', pattern: /Brave\/(\d+\.?\d*)/i },
  { name: 'Vivaldi', pattern: /Vivaldi\/(\d+\.?\d*)/i },
  { name: 'Android Browser', pattern: /Android.*Version\/(\d+\.?\d*)/i },
  { name: 'Internet Explorer', pattern: /MSIE (\d+\.?\d*)/i },
  { name: 'Internet Explorer', pattern: /Trident.*rv:(\d+\.?\d*)/i },
]

const OS_PATTERNS = [
  { name: 'Windows 11', pattern: /Windows NT 10\.0.*Win64.*x64.*(?:24H2|23H2|22H2)/i },
  { name: 'Windows 11', pattern: /Windows NT 11/i },
  { name: 'Windows 10', pattern: /Windows NT 10\.0/i },
  { name: 'Windows 8.1', pattern: /Windows NT 6\.3/i },
  { name: 'Windows 8', pattern: /Windows NT 6\.2/i },
  { name: 'Windows 7', pattern: /Windows NT 6\.1/i },
  { name: 'Windows Vista', pattern: /Windows NT 6\.0/i },
  { name: 'Windows XP', pattern: /Windows NT 5\.1/i },
  { name: 'Windows', pattern: /Windows/i },
  { name: 'iOS 17', pattern: /iPhone OS 17_|iPad OS 17_|CPU OS 17_/i },
  { name: 'iOS 16', pattern: /iPhone OS 16_|iPad OS 16_|CPU OS 16_/i },
  { name: 'iOS 15', pattern: /iPhone OS 15_|iPad OS 15_|CPU OS 15_/i },
  { name: 'iOS', pattern: /iPhone OS|iPad OS|CPU OS/i },
  { name: 'iOS', pattern: /iPhone|iPad|iPod/i },
  { name: 'Android 14', pattern: /Android 14/i },
  { name: 'Android 13', pattern: /Android 13/i },
  { name: 'Android 12', pattern: /Android 12/i },
  { name: 'Android 11', pattern: /Android 11/i },
  { name: 'Android', pattern: /Android/i },
  { name: 'macOS Sonoma', pattern: /Mac OS X 14_/i },
  { name: 'macOS Ventura', pattern: /Mac OS X 13_/i },
  { name: 'macOS Monterey', pattern: /Mac OS X 12_/i },
  { name: 'macOS Big Sur', pattern: /Mac OS X 11_/i },
  { name: 'macOS', pattern: /Mac OS X/i },
  { name: 'macOS', pattern: /Macintosh/i },
  { name: 'Linux', pattern: /X11; Linux/i },
  { name: 'Linux', pattern: /Linux/i },
  { name: 'Chrome OS', pattern: /CrOS/i },
  { name: 'Ubuntu', pattern: /Ubuntu/i },
  { name: 'Fedora', pattern: /Fedora/i },
  { name: 'FreeBSD', pattern: /FreeBSD/i },
  { name: 'OpenBSD', pattern: /OpenBSD/i },
]

const ENGINE_PATTERNS = [
  { name: 'Blink', pattern: /Chrome\/(\d+\.?\d*)/i },
  { name: 'Gecko', pattern: /Gecko\/(\d+)/i },
  { name: 'WebKit', pattern: /AppleWebKit\/(\d+\.?\d*)/i },
  { name: 'Presto', pattern: /Opera.*Presto\/(\d+\.?\d*)/i },
  { name: 'Trident', pattern: /Trident\/(\d+\.?\d*)/i },
  { name: 'EdgeHTML', pattern: /Edge\/(\d+\.?\d*)/i },
]

const BOT_PATTERNS = [
  { name: 'Googlebot', pattern: /Googlebot/i },
  { name: 'Bingbot', pattern: /bingbot/i },
  { name: 'Bingbot', pattern: /MSNBot/i },
  { name: 'YandexBot', pattern: /YandexBot/i },
  { name: 'Baidu Spider', pattern: /Baiduspider/i },
  { name: 'DuckDuckBot', pattern: /DuckDuckBot/i },
  { name: 'Slurp', pattern: /Yahoo! Slurp/i },
  { name: 'Facebot', pattern: /facebot/i },
  { name: 'Facebook External Hit', pattern: /facebookexternalhit/i },
  { name: 'Twitterbot', pattern: /Twitterbot/i },
  { name: 'Discordbot', pattern: /Discordbot/i },
  { name: 'TelegramBot', pattern: /TelegramBot/i },
  { name: 'Applebot', pattern: /Applebot/i },
  { name: 'SemrushBot', pattern: /SemrushBot/i },
  { name: 'AhrefsBot', pattern: /AhrefsBot/i },
  { name: 'MJ12bot', pattern: /MJ12bot/i },
  { name: 'cURL', pattern: /curl\/(\d+\.?\d*)/i },
  { name: 'Wget', pattern: /Wget\/(\d+\.?\d*)/i },
  { name: 'Postman', pattern: /PostmanRuntime\/(\d+\.?\d*)/i },
  { name: 'Python Requests', pattern: /python-requests/i },
  { name: 'Node.js', pattern: /node-fetch/i },
  { name: 'Scrapy', pattern: /Scrapy/i },
]

const MOBILE_INDICATORS = [
  /Mobile/i,
  /Android/i,
  /iPhone/i,
  /iPad/i,
  /iPod/i,
  /BlackBerry/i,
  /Windows Phone/i,
  /Symbian/i,
  /webOS/i,
  /IEMobile/i,
  /Opera Mini/i,
  /Opera Mobi/i,
  /UCWEB/i,
  /Fennec/i,
  /Maemo/i,
  /MeeGo/i,
]

const TABLET_INDICATORS = [
  /iPad/i,
  /Tablet/i,
  /Kindle/i,
  /Silk/i,
  /PlayBook/i,
]

export {
  EXAMPLE_UAS,
  EXAMPLE_LABELS,
  DEVICE_TYPES,
  BROWSER_PATTERNS,
  OS_PATTERNS,
  ENGINE_PATTERNS,
  BOT_PATTERNS,
  MOBILE_INDICATORS,
  TABLET_INDICATORS,
}
