
const ERROR_CODES = {
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  INVALID_EMPTY_STATE_TYPE: 'INVALID_EMPTY_STATE_TYPE',
  INVALID_NOTIFICATION_TYPE: 'INVALID_NOTIFICATION_TYPE',
  INVALID_SEVERITY: 'INVALID_SEVERITY',
  NOTIFICATION_QUEUE_FULL: 'NOTIFICATION_QUEUE_FULL',
  DUPLICATE_NOTIFICATION_ID: 'DUPLICATE_NOTIFICATION_ID',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_VISIBILITY_STATE: 'INVALID_VISIBILITY_STATE',
}

const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_STATE_TRANSITION]: '无效的状态转换',
  [ERROR_CODES.INVALID_EMPTY_STATE_TYPE]: '无效的空状态类型',
  [ERROR_CODES.INVALID_NOTIFICATION_TYPE]: '无效的通知类型',
  [ERROR_CODES.INVALID_SEVERITY]: '无效的严重级别',
  [ERROR_CODES.NOTIFICATION_QUEUE_FULL]: '通知队列已满',
  [ERROR_CODES.DUPLICATE_NOTIFICATION_ID]: '通知ID重复',
  [ERROR_CODES.INVALID_TOKEN]: '无效的加载令牌',
  [ERROR_CODES.INVALID_VISIBILITY_STATE]: '无效的可见性状态',
}

function getErrorMessage(code) {
  return ERROR_MESSAGES[code] || '未知错误'
}

function createError(code, customMessage = null) {
  return {
    errorCode: code,
    errorMessage: customMessage || getErrorMessage(code),
  }
}

export {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  createError,
}
